function head5(num, eyebrow, a, b, top = 90) { return `<div class="abs h5" style="left:110px;top:${top}px"><span class="eyebrow" style="color:#67E8F9"><span class="n" style="border-color:rgba(103,232,249,.5)">${num}</span>${eyebrow}</span><div style="font-size:56px;font-weight:900;letter-spacing:-2px;margin-top:8px">${a} <span class="cyant">${b}</span></div></div>`; }
function headIn(r, lt) { const h = $('.h5', r); if (!h) return; const k = P(lt, 0.05, 0.7, E.out5); S(h, { y: (1 - k) * 24, op: k }); }
const bub = (side, html, cls = '', st = '') => `<div class="${cls}" style="${side === 'r' ? 'margin-left:auto;background:#0C684F;color:#fff;border-radius:16px 16px 4px 16px' : 'background:#fff;color:#0E261F;border-radius:16px 16px 16px 4px;border:1px solid #EAE3D4'};max-width:86%;padding:10px 14px;font-size:15px;margin-top:10px;${st}">${html}</div>`;

scene({ id: 'x-copilot', dur: 8, act: 5, label: X5, mood: MD,
  html: `${head5('09', 'Hands-free & multilingual', 'Drivers talk.', 'Everyone understands.')}
    ${phone('pa', { x: 300, y: 205, scale: 0.78, clip: false, dark: true, inner: `<div class="app" style="background:#0B1512;color:#EEF1E9"><div class="apphdr" style="background:#0E1714;border-color:#F2C14E"><img src="logo-light.svg"></div>
      <div class="abs" style="left:18px;right:18px;top:120px"><div class="lbl" style="color:#67E8F9">Driver copilot · listening</div>
      <div class="row" style="gap:4px;height:70px;margin-top:14px;justify-content:center" id="dw">${[...Array(28)].map(() => '<i style="width:5px;border-radius:3px;background:#22D3EE;height:50px"></i>').join('')}</div>
      <div id="dc1" style="margin-top:12px;font-size:28px;font-weight:900;text-align:center;opacity:0">“Accept”</div>
      <div id="dr1" style="margin-top:12px;padding:14px;border-radius:16px;background:#0C684F;opacity:0"><b>Ride accepted</b><div style="font-size:13px;opacity:.85">Pickup in 4 min · Farmgate</div></div>
      <div id="dc2" style="margin-top:22px;font-size:28px;font-weight:900;text-align:center;opacity:0">“I’ve arrived”</div>
      <div id="dr2" style="margin-top:12px;padding:14px;border-radius:16px;background:#132420;border:1px solid #1E3530;opacity:0"><b>Rider notified</b><div style="font-size:13px;opacity:.7">Waiting for Tom to confirm</div></div></div></div>` })}
    ${panel('ch', 900, 230, 900, 640, `<div style="padding:26px"><div class="lbl" style="color:#67E8F9">Live translated chat</div>
      <div class="row" style="gap:12px;margin-top:14px"><div class="av" style="width:44px;height:44px;background:#2563EB">T</div><div><b style="font-size:18px">Tom · visiting from London</b><div style="font-size:13px;color:rgba(255,255,255,.6)">writes in English · Rahim reads Bangla</div></div></div>
      <div id="m1" style="margin-top:18px;max-width:640px;background:#fff;color:#0E261F;border-radius:18px 18px 18px 4px;padding:14px 18px;opacity:0"><div style="font-size:19px;font-weight:600">Hi! I’m at the hotel’s main gate, blue umbrella.</div><div id="m1t" class="bn" style="margin-top:8px;padding-top:8px;border-top:1px dashed #CBD5E1;color:#0C684F;font-size:19px;font-weight:600;opacity:0">হাই! আমি হোটেলের মূল গেটে, হাতে নীল ছাতা।</div></div>
      <div id="m2" style="margin-top:14px;margin-left:auto;max-width:560px;background:#0C684F;color:#fff;border-radius:18px 18px 4px 18px;padding:14px 18px;opacity:0"><div class="bn" style="font-size:19px;font-weight:600">আসছি, দুই মিনিট লাগবে।</div><div id="m2t" style="margin-top:8px;padding-top:8px;border-top:1px dashed rgba(255,255,255,.4);font-size:19px;font-weight:600;opacity:0">Coming — two minutes.</div></div>
      <div id="qr" class="row" style="gap:8px;margin-top:16px;opacity:0">${['I’m outside', 'Running late', 'Call me'].map((x) => `<span class="chip" style="background:rgba(255,255,255,.1);color:#fff">${x}</span>`).join('')}</div></div>`)}`,
  caps: [[0.4, 4.0, 'Drivers keep both hands on the wheel: “Accept”, “I’ve arrived” — done by voice.'], [4.1, 8.2, 'A tourist types in English, Rahim reads Bangla — and replies, translated back instantly.']],
  update(lt, d, r) { headIn(r, lt); devIn($('#pa', r), lt, { from: 'left', base: 0.78, ry: 8 }); panelIn($('#ch', r), lt, 0.3);
    const listen = (lt > 0.6 && lt < 1.6) || (lt > 2.4 && lt < 3.3); $$('#dw i', r).forEach((el, i) => { el.style.transform = `scaleY(${listen ? 0.2 + 0.8 * Math.abs(Math.sin(lt * 10 + i * 0.6)) : 0.1})`; });
    S($('#dc1', r), { op: P(lt, 1.0, 1.3) }); S($('#dr1', r), { op: P(lt, 1.6, 1.9) }); S($('#dc2', r), { op: P(lt, 2.8, 3.1) }); S($('#dr2', r), { op: P(lt, 3.4, 3.7) });
    S($('#m1', r), { op: P(lt, 4.2, 4.6) }); S($('#m1t', r), { op: P(lt, 5.0, 5.5) }); S($('#m2', r), { op: P(lt, 6.0, 6.4) }); S($('#m2t', r), { op: P(lt, 6.8, 7.2) }); S($('#qr', r), { op: P(lt, 7.4, 7.8) }); } });

scene({ id: 'x-support', dur: 8.5, act: 5, label: X5, mood: MD,
  html: () => { const w = 540, h = 300; const p = proj([23.765, 90.395], 42000, w, h); const plan = road('Airport Road', [23.765, 90.395], 42000, w, h).slice(5, 12); const det = [plan[0], plan[1], [plan[1][0] - 90, plan[1][1] + 30], [plan[3][0] - 110, plan[3][1] + 10], plan[4], plan[5], plan[6]];
    return `${head5('10', 'AI support agent', 'Overcharged?', 'Sorted in seconds.')}
    ${panel('sp', 110, 260, 820, 650, `<div style="padding:24px 26px;height:100%;display:flex;flex-direction:column"><div class="row" style="gap:12px"><div class="av" style="width:42px;height:42px;background:#0C684F">${icb('headset', 22, '#fff', 2.2)}</div><div><b style="font-size:18px">Cholo Support</b><div style="font-size:13px;color:#67E8F9">AI agent · can issue refunds</div></div></div>
      <div style="flex:1;margin-top:8px">${bub('r', 'I was overcharged on my last trip.', 'sb', 'opacity:0')}
      ${bub('l', 'Checking trip <b>JT-2026-000731</b>… The driver took a 2.4 km detour around Tejgaon.', 'sb', 'opacity:0')}
      ${bub('l', 'You paid <b>৳260</b>. The fair fare for the planned route is <b>৳200</b>.', 'sb', 'opacity:0')}
      ${bub('l', `<div class="row" style="gap:10px">${icb('check', 22, '#0C684F', 3)}<div><b>৳60 refunded to your wallet.</b><div style="font-size:12px;color:#5E6C65">Within policy · driver notified · ticket closed</div></div></div>`, 'sb', 'opacity:0;border-color:#0C684F')}</div>
      <div id="audit" style="font-family:monospace;font-size:14px;color:#67E8F9;background:rgba(0,0,0,.35);border-radius:12px;padding:10px 14px;opacity:0">audit · REFUND_ISSUED · trips #731 · ৳60 · by AI agent · policy cap ৳150</div></div>`)}
    ${panel('mp', 970, 260, 840, 650, `<div style="padding:24px 26px"><div class="lbl" style="color:#67E8F9">GPS trace replay</div><div class="abs" style="left:26px;top:70px;width:${w + 250}px;height:${h + 140}px;border-radius:18px;overflow:hidden">${dmap({ w: w + 250, h: h + 140, center: [23.765, 90.395], k: 42000, theme: 'dark' })}
      <svg class="abs" viewBox="0 0 ${w} ${h}" style="left:125px;top:70px;width:${w}px;height:${h}px;overflow:visible"><polyline points="${polyStr(plan)}" fill="none" stroke="#22C55E" stroke-width="7" stroke-linecap="round" stroke-dasharray="14 10"/><polyline id="dt" points="${polyStr(det)}" fill="none" stroke="#EF4444" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></svg></div>
      <div class="row" style="position:absolute;left:26px;bottom:26px;gap:24px;font-size:18px;font-weight:700"><span class="row" style="gap:8px"><i style="width:28px;height:6px;background:#22C55E;border-radius:3px"></i>Planned 7.2 km · ৳200</span><span class="row" style="gap:8px"><i style="width:28px;height:6px;background:#EF4444;border-radius:3px"></i>Driven 9.6 km · ৳260</span></div></div>`)}`; },
  caps: [[0.4, 4.4, '“I was overcharged.” The agent replays the GPS trace and finds a 2.4 km detour.'], [4.5, 8.7, 'Within policy, it refunds ৳60 by itself — and every action goes into the audit log.']],
  sfx: [[6.0, 'coin']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#sp', r), lt, 0.2); panelIn($('#mp', r), lt, 0.35);
    $$('.sb', r).forEach((el, i) => { const k = P(lt, 0.9 + i * 1.6, 1.3 + i * 1.6); S(el, { op: k, y: (1 - k) * 14 }); });
    const dt = $('#dt', r); const len = dt.getTotalLength(); dt.style.strokeDasharray = len; dt.style.strokeDashoffset = len * (1 - P(lt, 2.2, 4.0, E.inOut)); S($('#audit', r), { op: P(lt, 6.6, 7.1) }); } });

const SQL = `SELECT date_trunc('hour', r.created_at) AS hour,\n       count(*) FILTER (WHERE t.status = 'cancelled') AS cancelled,\n       avg(w.rain_mm) AS rain\nFROM ride_requests r JOIN zones z ON z.id = r.zone_id\nLEFT JOIN trips t ON t.request_id = r.id\nWHERE z.name = 'Uttara' AND r.created_at::date = '2026-09-29'\nGROUP BY 1 ORDER BY 1;`;
scene({ id: 'x-ask', dur: 8.5, act: 5, label: X5, mood: MD,
  html: `${head5('11', 'Ask Cholo', 'Ask in plain words.', 'Get the answer.')}
    ${panel('ak', 110, 250, 1700, 680, `<div style="padding:26px 30px"><div class="row" style="gap:14px;padding:16px 20px;border-radius:18px;background:rgba(255,255,255,.08);border:1.5px solid rgba(103,232,249,.35)">${icb('sparkle', 26, '#67E8F9', 2)}<span id="aq" style="font-size:25px;font-weight:600"></span></div>
      <div class="row" style="gap:24px;margin-top:22px;align-items:flex-start"><pre id="sql" style="flex:1;margin:0;height:420px;font-size:16px;line-height:1.6;color:#A5F3FC;background:rgba(0,0,0,.35);border-radius:16px;padding:18px 20px;white-space:pre-wrap;font-family:monospace"></pre>
      <div style="width:760px"><div id="chart" style="height:300px;position:relative;border-radius:16px;background:rgba(0,0,0,.25);padding:18px"><div class="lbl">Cancellations per hour · Uttara · last Tuesday</div>
        <div class="abs" style="left:18px;right:18px;bottom:36px;height:200px;display:flex;align-items:flex-end;gap:8px">${[6, 5, 7, 6, 8, 7, 9, 8, 10, 9, 11, 12, 34, 41, 29, 14, 9].map((v, i) => `<div class="cb" style="flex:1;height:${v * 4.4}px;border-radius:6px 6px 2px 2px;background:${v > 25 ? 'linear-gradient(180deg,#FFE58A,#E88A12)' : 'linear-gradient(180deg,#67E8F9,#0E7490)'};transform-origin:50% 100%"></div>`).join('')}</div>
        <div class="abs row" style="left:18px;right:18px;bottom:10px;justify-content:space-between;font-size:13px;color:rgba(255,255,255,.5)"><span>2 PM</span><span>6 PM</span><span>10 PM</span></div></div>
      <div id="ans" class="card" style="position:relative;margin-top:16px;padding:18px 22px;opacity:0"><div class="row" style="gap:10px;font-size:14px;font-weight:800;color:#0C684F">${icb('sparkle', 18, '#0C684F', 2.4)}ANSWER</div><div style="font-size:20px;font-weight:700;margin-top:6px">Rain started at 6:10 PM. Online drivers in Uttara dropped 40% within 20 minutes, so cancellations tripled.</div></div></div></div></div>`)}`,
  caps: [[0.4, 8.7, '“Why did cancellations spike in Uttara last Tuesday?” Cholo writes the SQL, draws the chart and explains.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#ak', r), lt, 0.2); typeText($('#aq', r), 'Why did cancellations spike in Uttara last Tuesday evening?', lt, 0.6, 30); typeText($('#sql', r), SQL, lt, 2.4, 160);
    $$('.cb', r).forEach((el, i) => { const k = P(lt, 4.4 + i * 0.05, 4.9 + i * 0.05, E.back); el.style.transform = `scaleY(${Math.max(0, k)})`; }); const ka = P(lt, 6.0, 6.5, E.back); S($('#ans', r), { op: clamp(ka * 2), y: (1 - ka) * 20 }); } });

const BD = { c: [23.785, 90.405], k: 30000, w: 1060, h: 700 };
scene({ id: 'x-dispatch', dur: 9, act: 5, label: X5, mood: MD,
  html: () => `${head5('12', 'Batched AI dispatch', 'Not the nearest driver.', 'The best match for everyone.')}
    ${panel('dm', 110, 250, BD.w, BD.h, dmap({ w: BD.w, h: BD.h, center: BD.c, k: BD.k, theme: 'neon', bld: false }) + cnv('dc', BD.w, BD.h) + `<div class="abs row" style="left:20px;top:18px;gap:10px"><span class="tag" id="mode" style="background:rgba(239,68,68,.2);color:#FCA5A5">GREEDY · NEAREST FIRST</span><span class="tag" style="background:rgba(255,255,255,.1);color:#fff" id="win">BATCH WINDOW 3.0 s</span></div>`)}
    <div class="glassc" id="mt" style="left:1210px;top:250px;width:600px;height:700px;padding:30px">
      <div class="lbl" style="color:#67E8F9">Total pickup time · 8 riders</div><div id="tot" style="font-size:96px;font-weight:900;margin-top:10px;font-variant-numeric:tabular-nums">47 min</div>
      <div id="sav" class="goldt" style="font-size:40px;font-weight:900;opacity:0">−34% waiting</div>
      <div style="margin-top:30px;font-size:21px;line-height:1.5;color:rgba(255,255,255,.75);font-weight:500">Cholo collects requests for three seconds, then solves the assignment for all riders at once — minimising total wait, not just the first rider’s.</div>
      <div class="row" style="gap:12px;margin-top:26px;font-size:18px;font-weight:700"><span class="row" style="gap:8px"><i style="width:14px;height:14px;border-radius:50%;background:#FBBF2E"></i>Riders</span><span class="row" style="gap:8px"><i style="width:14px;height:14px;border-radius:4px;background:#22D3EE"></i>Drivers</span></div></div>`,
  caps: [[0.4, 4.4, 'Nearest-driver dispatch makes some riders wait far too long.'], [4.5, 8.7, 'Batched matching solves for everyone at once — total waiting drops by a third.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#dm', r), lt, 0.2); panelIn($('#mt', r), lt, 0.35);
    if (!r.__pts) { const rr = srand(21); r.__R = [...Array(8)].map(() => [140 + rr() * 780, 110 + rr() * 500]); r.__D = [...Array(10)].map(() => [100 + rr() * 860, 90 + rr() * 540]);
      const used = new Set(); r.__greedy = r.__R.map((p) => { let b = -1, bd = 1e9; r.__D.forEach((q, j) => { if (used.has(j)) return; const dd = Math.hypot(p[0] - q[0], p[1] - q[1]); if (dd < bd) { bd = dd; b = j; } }); used.add(b); return b; });
      let best = r.__greedy.slice(); const cost = (a) => a.reduce((s, j, i) => s + Math.hypot(r.__R[i][0] - r.__D[j][0], r.__R[i][1] - r.__D[j][1]), 0);
      for (let it = 0; it < 4000; it++) { const i = Math.floor(rr() * 8), k = Math.floor(rr() * 10); const c = best.slice(); const o = c.indexOf(k); if (o >= 0) { c[o] = c[i]; } c[i] = k; if (cost(c) < cost(best)) best = c; } r.__opt = best; r.__pts = 1; }
    const g = $('#dc', r).getContext('2d'); g.clearRect(0, 0, BD.w, BD.h); const kk = P(lt, 4.6, 6.0, E.inOut); const tw = P(lt, 1.0, 2.2);
    r.__R.forEach((p, i) => { const a = r.__D[r.__greedy[i]], b = r.__D[r.__opt[i]]; const q = [L(a[0], b[0], kk), L(a[1], b[1], kk)]; g.strokeStyle = kk > 0.5 ? `rgba(34,197,94,${0.9 * tw})` : `rgba(239,68,68,${0.9 * tw})`; g.lineWidth = 3; g.setLineDash([10, 8]); g.lineDashOffset = -lt * 30; g.beginPath(); g.moveTo(p[0], p[1]); g.lineTo(L(p[0], q[0], tw), L(p[1], q[1], tw)); g.stroke(); });
    g.setLineDash([]); r.__D.forEach(([x, y]) => { g.fillStyle = '#22D3EE'; g.fillRect(x - 8, y - 8, 16, 16); }); r.__R.forEach(([x, y]) => { g.fillStyle = '#FBBF2E'; g.beginPath(); g.arc(x, y, 9, 0, 7); g.fill(); g.strokeStyle = 'rgba(251,191,46,.4)'; g.lineWidth = 2; g.beginPath(); g.arc(x, y, 9 + ((lt * 1.3) % 1) * 16, 0, 7); g.stroke(); });
    $('#tot', r).textContent = `${Math.round(L(47, 31, kk))} min`; S($('#sav', r), { op: P(lt, 6.0, 6.5) }); $('#mode', r).textContent = kk > 0.5 ? 'BATCHED · OPTIMAL' : 'GREEDY · NEAREST FIRST'; $('#mode', r).style.background = kk > 0.5 ? 'rgba(34,197,94,.2)' : 'rgba(239,68,68,.2)'; $('#mode', r).style.color = kk > 0.5 ? '#86EFAC' : '#FCA5A5';
    $('#win', r).textContent = `BATCH WINDOW ${Math.max(0, 3 - ((lt * 1.2) % 3)).toFixed(1)} s`; } });

const FC = { c: [23.785, 90.4], k: 16000, w: 1060, h: 700 };
scene({ id: 'x-forecast', dur: 9, act: 5, label: X5, mood: MD,
  html: () => `${head5('13', 'Demand forecasting', 'Know where riders will be.', 'Send drivers there first.')}
    ${panel('fm', 110, 250, FC.w, FC.h, dmap({ w: FC.w, h: FC.h, center: FC.c, k: FC.k, theme: 'neon', bld: false }) + cnv('fc', FC.w, FC.h) + `<div class="abs row" style="left:20px;top:18px;gap:8px">${['NOW', '+15 MIN', '+30 MIN', '+60 MIN'].map((x) => `<span class="tag ft" style="background:rgba(255,255,255,.1);color:#fff">${x}</span>`).join('')}</div>
      <div class="card" id="rp" style="left:520px;top:440px;width:440px;padding:16px 18px;border-radius:18px;opacity:0"><div class="row" style="gap:10px"><div style="width:42px;height:42px;border-radius:12px;background:#FBBF2E;display:flex;align-items:center;justify-content:center">${icb('nav', 22, '#0E261F', 2.4)}</div><div><b style="font-size:17px">Go to Gulshan 1</b><div style="font-size:13px;color:#5E6C65">12 requests expected in 20 min · ~৳600</div></div></div></div>`)}
    <div class="glassc" id="fv" style="left:1210px;top:250px;width:600px;height:700px;padding:30px"><div class="lbl" style="color:#67E8F9">Forecast vs actual · Gulshan</div>
      <svg viewBox="0 0 540 300" style="width:540px;height:300px;margin-top:20px;overflow:visible"><polyline id="fa" points="${[...Array(24)].map((_, i) => `${i * 23},${260 - (60 + Math.sin(i / 3.2) * 70 + (i > 15 ? 70 : 0) + Math.sin(i * 1.7) * 12)}`).join(' ')}" fill="none" stroke="#FBBF2E" stroke-width="4"/><polyline id="ff" points="${[...Array(24)].map((_, i) => `${i * 23},${260 - (60 + Math.sin(i / 3.2) * 70 + (i > 15 ? 70 : 0))}`).join(' ')}" fill="none" stroke="#22D3EE" stroke-width="4" stroke-dasharray="10 8"/></svg>
      <div class="row" style="gap:20px;font-size:18px;font-weight:700;margin-top:10px"><span class="row" style="gap:8px"><i style="width:26px;height:5px;background:#FBBF2E"></i>Actual</span><span class="row" style="gap:8px"><i style="width:26px;height:5px;background:#22D3EE"></i>Forecast</span></div>
      <div style="margin-top:30px" class="lbl">Accuracy, last 7 days</div><div class="cyant" id="acc" style="font-size:80px;font-weight:900">0%</div></div>`,
  caps: [[0.4, 4.5, 'Cholo forecasts demand for every hexagon of Dhaka — 15, 30 and 60 minutes ahead.'], [4.6, 8.7, 'Idle drivers are told where to go before the rush, so riders wait less and drivers earn more.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#fm', r), lt, 0.2); panelIn($('#fv', r), lt, 0.35);
    if (!r.__h) r.__h = hexGrid(FC.w, FC.h, 30); const step = clamp(Math.floor((lt - 0.8) / 1.4), 0, 3); $$('.ft', r).forEach((el, i) => { el.style.background = i === step ? '#22D3EE' : 'rgba(255,255,255,.1)'; el.style.color = i === step ? '#03141B' : '#fff'; });
    const hot = [[23.7806, 90.4167], [23.7925, 90.4148], [23.751, 90.393], [23.73, 90.418]].map(([a, b]) => proj(FC.c, FC.k, FC.w, FC.h)(a, b)); const g = $('#fc', r).getContext('2d'); g.clearRect(0, 0, FC.w, FC.h); const ka = P(lt, 0.5, 1.5);
    for (const [x, y] of r.__h) { let v = 0; hot.forEach(([hx, hy], i) => { v += Math.max(0, 1 - Math.hypot(x - hx, y - hy) / (150 + step * 40 * (i === 0 ? 1.6 : 0.6))) * (i === 0 ? 0.6 + step * 0.15 : 0.55); }); v = Math.min(1, v) * ka; if (v < 0.06) continue; const pth = new Path2D(hexPath(x, y, 28)); g.fillStyle = `rgba(${Math.round(L(34, 251, v))},${Math.round(L(211, 120, v))},${Math.round(L(238, 40, v))},${0.1 + v * 0.45})`; g.fill(pth); }
    const kr = P(lt, 5.0, 5.5, E.back); S($('#rp', r), { s: Math.max(0, kr), op: clamp(kr * 2) });
    ['#fa', '#ff'].forEach((s, i) => { const el = $(s, r); const len = el.getTotalLength(); el.style.strokeDasharray = i ? '10 8' : len; if (!i) el.style.strokeDashoffset = len * (1 - P(lt, 1.0, 3.5, E.inOut)); el.style.opacity = i ? P(lt, 1.5, 2.2) : 1; }); $('#acc', r).textContent = `${Math.round(94 * P(lt, 3.5, 5.0))}%`; } });

scene({ id: 'x-surge', dur: 8, act: 5, label: X5, mood: MD,
  html: () => `${head5('14', 'Fair pricing, explained', 'Surge you understand.', 'ETAs you can trust.')}
    ${panel('s1', 110, 250, 840, 680, cnv('sc', 840, 520) + `<div class="card" id="se" style="left:30px;top:430px;width:780px;padding:18px 22px;border-radius:20px;opacity:0"><div class="row" style="justify-content:space-between"><span style="font-size:15px;font-weight:800;color:#9A6A0E;letter-spacing:2px">WHY THE PRICE IS HIGHER</span><span class="tag" style="background:#FFF6DC;color:#9A6A0E">CAPPED AT 2.0×</span></div>
      <div class="row" style="gap:18px;margin-top:8px"><span class="goldt" style="font-size:56px;font-weight:900">1.4×</span><div style="font-size:19px;font-weight:600">It’s raining and 60% fewer drivers are online near you. Prices ease as drivers arrive.</div></div></div>`)}
    ${panel('s2', 990, 250, 820, 680, `<div style="padding:28px"><div class="lbl" style="color:#67E8F9">Machine-learned ETA</div><div class="row" style="gap:16px;margin-top:20px;align-items:baseline"><span style="font-size:22px;color:rgba(255,255,255,.6);font-weight:600">Pickup in</span><span id="eta" style="font-size:110px;font-weight:900;font-variant-numeric:tabular-nums">7 min</span></div>
      <div id="etan" style="font-size:19px;color:#67E8F9;font-weight:700;opacity:0">Corrected for the Farmgate signal and school traffic</div>
      <div class="lbl" style="margin-top:34px">Error by week (MAPE)</div><svg viewBox="0 0 760 200" style="width:760px;height:200px;margin-top:10px;overflow:visible"><polyline id="mape" points="${[22, 19, 17, 15, 13, 11, 10, 9, 8, 7, 6.5, 6].map((v, i) => `${i * 68},${200 - v * 8}`).join(' ')}" fill="none" stroke="#22D3EE" stroke-width="5" stroke-linecap="round"/></svg>
      <div class="row" style="justify-content:space-between;font-size:16px;color:rgba(255,255,255,.5)"><span>22% error</span><span class="goldt" style="font-size:24px;font-weight:900">6% error</span></div></div>`)}`,
  caps: [[0.4, 4.0, 'When prices rise, Cholo says why — and surge is smooth between areas and always capped.'], [4.1, 7.7, 'ETAs are learned from real trips, so “5 minutes” really means five minutes.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#s1', r), lt, 0.2); panelIn($('#s2', r), lt, 0.35);
    if (!r.__h) r.__h = hexGrid(840, 420, 30); const g = $('#sc', r).getContext('2d'); g.clearRect(0, 0, 840, 520); const ka = P(lt, 0.5, 1.6);
    for (const [x, y] of r.__h) { const v = clamp(1 - Math.hypot(x - 420, y - 200) / 360) * ka; const m = 1 + v * 0.9; const pth = new Path2D(hexPath(x, y + 10, 28)); g.fillStyle = `rgba(${Math.round(L(30, 251, v))},${Math.round(L(120, 160, v))},${Math.round(L(110, 40, v))},${0.25 + v * 0.55})`; g.fill(pth); if (v > 0.55 && (Math.round(x) % 3 === 0)) { g.fillStyle = '#03141B'; g.font = 'bold 13px Inter'; g.textAlign = 'center'; g.fillText(`${m.toFixed(1)}×`, x, y + 15); } }
    const ke = P(lt, 2.0, 2.5, E.back); S($('#se', r), { op: clamp(ke * 2), y: (1 - ke) * 30 });
    $('#eta', r).textContent = `${lt > 5.0 ? 5 : lt > 4.6 ? 6 : 7} min`; S($('#etan', r), { op: P(lt, 5.0, 5.4) }); const mp = $('#mape', r); const len = mp.getTotalLength(); mp.style.strokeDasharray = len; mp.style.strokeDashoffset = len * (1 - P(lt, 4.4, 6.6, E.inOut)); } });

scene({ id: 'x-pool', dur: 9, act: 5, label: X5, mood: MD,
  html: `${head5('15', 'Smarter trips', 'Share it. Order it.', 'Lock the price.')}
    ${panel('q1', 110, 260, 540, 640, `<div style="padding:26px"><div class="lbl" style="color:#67E8F9">Cholo Pool</div><svg viewBox="0 0 490 300" style="width:490px;height:300px;margin-top:16px"><path id="pr1" d="M30 250 C 120 230, 180 160, 260 150 S 420 80, 470 40" fill="none" stroke="#FBBF2E" stroke-width="8" stroke-linecap="round"/><path id="pr2" d="M60 60 C 120 110, 200 150, 260 150" fill="none" stroke="#22D3EE" stroke-width="8" stroke-linecap="round"/>
      <circle cx="30" cy="250" r="12" fill="#FBBF2E"/><circle cx="60" cy="60" r="12" fill="#22D3EE"/><circle cx="470" cy="40" r="12" fill="#fff"/><g id="pc"><rect x="-16" y="-9" width="32" height="18" rx="6" fill="#0C684F"/></g></svg>
      <div class="row" style="gap:16px;margin-top:10px"><div class="ucard" style="flex:1;padding:12px 14px"><div style="font-size:13px;color:#5E6C65;font-weight:700">Each pays</div><div class="row" style="gap:8px;align-items:baseline"><span style="font-size:18px;color:#94A3B8;text-decoration:line-through;font-weight:700">৳180</span><span id="pf" style="font-size:32px;font-weight:900;color:#0C684F">৳112</span></div></div>
      <div class="ucard" style="flex:1;padding:12px 14px"><div style="font-size:13px;color:#5E6C65;font-weight:700">Saved</div><div style="font-size:26px;font-weight:900;color:#0C684F">38% · 1.2 kg CO₂</div></div></div></div>`)}
    ${panel('q2', 690, 260, 540, 640, `<div style="padding:26px"><div class="lbl" style="color:#67E8F9">Multi-stop optimizer</div><div style="position:relative;height:330px;margin-top:20px">${[['Bank', 'Motijheel', '#2563EB'], ['Pharmacy', 'Dhanmondi 27', '#DC2626'], ['Home', 'Mirpur 10', '#0C684F']].map(([n, s, c], i) => `<div class="ucard st2 row" data-i="${i}" style="position:absolute;left:0;right:0;top:${i * 100}px;gap:14px;padding:16px 18px"><div style="width:44px;height:44px;border-radius:12px;background:${c};color:#fff;display:flex;align-items:center;justify-content:center;font-weight:900" class="sn">${i + 1}</div><div><b style="font-size:19px">${n}</b><div style="font-size:14px;color:#5E6C65">${s}</div></div></div>`).join('')}</div>
      <div class="row" id="so" style="gap:10px;font-size:20px;font-weight:800;opacity:0">${icb('check', 24, '#67E8F9', 3)}Best order found · saves 14 min</div></div>`)}
    ${panel('q3', 1270, 260, 540, 640, `<div style="padding:26px"><div class="lbl" style="color:#67E8F9">Guaranteed upfront fare</div><div style="margin-top:40px;display:flex;justify-content:center"><div id="gb" style="width:260px;height:260px;border-radius:50%;border:10px solid #FBBF2E;display:flex;flex-direction:column;align-items:center;justify-content:center;box-shadow:0 0 60px rgba(251,191,46,.35)"><div style="font-size:18px;font-weight:800;letter-spacing:3px;color:#FBBF2E">GUARANTEED</div><div style="font-size:72px;font-weight:900">৳182</div></div></div>
      <div style="margin-top:34px;text-align:center;font-size:21px;font-weight:600;color:rgba(255,255,255,.8)">Traffic jam? Detour? The price you saw is the price you pay.</div></div>`)}`,
  caps: [[0.4, 3.2, 'Cholo Pool: two riders going the same way share one car and each pays less.'], [3.3, 6.1, 'Add three stops and Cholo puts them in the fastest order — one fare.'], [6.2, 8.7, 'And the upfront fare is guaranteed, whatever the traffic does.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#q1', r), lt, 0.2); panelIn($('#q2', r), lt, 0.35); panelIn($('#q3', r), lt, 0.5);
    ['#pr1', '#pr2'].forEach((s, i) => { const el = $(s, r); const len = el.getTotalLength(); el.style.strokeDasharray = len; el.style.strokeDashoffset = len * (1 - P(lt, 0.8 + i * 0.3, 2.2 + i * 0.3, E.inOut)); });
    const p1 = $('#pr1', r); const pt = p1.getPointAtLength(p1.getTotalLength() * P(lt, 1.2, 3.4, E.inOut)); $('#pc', r).setAttribute('transform', `translate(${pt.x},${pt.y})`); $('#pf', r).textContent = `৳${Math.round(L(180, 112, P(lt, 2.2, 3.0)))}`;
    const order = lt > 4.6 ? [1, 2, 0] : [0, 1, 2]; const kk = P(lt, 4.4, 5.2, E.inOut); $$('.st2', r).forEach((el) => { const i = +el.dataset.i; const from = i * 100, to = order.indexOf(i) * 100; el.style.top = `${lt < 4.4 ? from : L(from, to, kk)}px`; $('.sn', el).textContent = (lt < 4.8 ? i : order.indexOf(i)) + 1; }); S($('#so', r), { op: P(lt, 5.3, 5.7) });
    const kg = P(lt, 6.2, 6.8, E.back); S($('#gb', r), { s: L(0.6, 1, Math.max(0, kg)) * (1 + 0.02 * Math.sin(lt * 4)), op: clamp(kg * 2) }); } });

const DEM = [10, 7, 5, 4, 5, 14, 38, 78, 96, 82, 52, 44, 48, 46, 44, 50, 66, 88, 100, 92, 70, 46, 30, 18];
scene({ id: 'x-peak', dur: 8, act: 5, label: X5, mood: MD,
  html: `${head5('16', 'Peak hours, sorted', 'Beat the rush.', 'Know before you go.')}
    ${panel('pk', 110, 260, 1100, 640, `<div style="padding:30px"><div class="row" style="justify-content:space-between"><div><div class="lbl">Demand today · Dhaka</div><div style="font-size:32px;font-weight:800;margin-top:4px">Rides per hour</div></div><span class="row" style="gap:10px;font-size:17px;font-weight:700"><i style="width:14px;height:14px;border-radius:4px;background:linear-gradient(#FFE58A,#E88A12)"></i>Peak</span></div>
      <div class="abs" style="left:30px;right:30px;bottom:70px;height:360px">${DEM.map((v, i) => `<div class="pb abs" style="left:${i * 43}px;bottom:0;width:30px;height:${v * 3.5}px;border-radius:7px 7px 3px 3px;transform-origin:50% 100%;background:${v > 75 ? 'linear-gradient(180deg,#FFE58A,#E88A12)' : 'linear-gradient(180deg,#67E8F9,#0E7490)'}"></div>`).join('')}
        <div id="now" class="abs" style="bottom:-10px;height:390px;width:2px;background:#fff"><div style="position:absolute;top:-32px;left:-30px;width:62px;text-align:center;font-size:14px;font-weight:800;background:#fff;color:#0E261F;border-radius:8px;padding:3px 0">NOW</div></div></div>
      <div class="abs row" style="left:30px;right:30px;bottom:30px;justify-content:space-between;font-size:16px;color:rgba(255,255,255,.55);font-weight:600"><span>12 AM</span><span>6 AM</span><span>12 PM</span><span>6 PM</span><span>11 PM</span></div></div>`)}
    <div class="card" id="nt" style="left:1250px;top:280px;width:560px;padding:20px 24px;border-radius:24px;opacity:0"><div class="row" style="gap:16px"><div style="width:54px;height:54px;border-radius:16px;background:#0C684F;display:flex;align-items:center;justify-content:center;flex:none">${icb('bell', 28, '#FFE58A', 2.2)}</div><div><div style="font-weight:800;font-size:21px">Price drop on your route</div><div style="font-size:17px;color:#5E6C65;margin-top:2px">Home → Office is 20% cheaper now</div></div></div></div>
    <div class="glassc" id="fl" style="left:1250px;top:470px;width:560px;padding:24px 28px;opacity:0"><div class="lbl" style="color:#67E8F9">Fare lock</div><div class="row" style="justify-content:space-between;margin-top:8px"><span style="font-size:52px;font-weight:900">৳180</span><span id="cd" style="font-size:40px;font-weight:800;font-variant-numeric:tabular-nums;color:#FBBF2E">9:59</span></div><div style="font-size:18px;color:rgba(255,255,255,.7);font-weight:600">Locked for 10 minutes — book whenever you’re ready</div></div>`,
  caps: [[0.4, 7.7, 'See Dhaka’s peak hours, lock a fare for ten minutes, and get pinged when your route gets cheaper.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#pk', r), lt, 0.2); $$('.pb', r).forEach((el, i) => { const k = P(lt, 0.6 + i * 0.04, 1.2 + i * 0.04, E.back); el.style.transform = `scaleY(${Math.max(0, k)})`; });
    const kn = P(lt, 1.6, 4.8, E.inOut); $('#now', r).style.left = `${L(6, 17.3, kn) * 43 + 14}px`; S($('#now', r), { op: P(lt, 1.6, 2.0) });
    const k1 = P(lt, 3.0, 3.6, E.back); S($('#nt', r), { y: (1 - k1) * -50, op: clamp(k1 * 2) }); const k2 = P(lt, 2.2, 2.8, E.back); S($('#fl', r), { s: Math.max(0, k2), op: clamp(k2 * 2) }); const secs = 599 - Math.floor(clamp(lt - 2.4, 0, 10)); $('#cd', r).textContent = `${Math.floor(secs / 60)}:${String(secs % 60).padStart(2, '0')}`; } });
