const FL = { c: [23.74, 90.396], k: 16000, w: 1180, h: 760 };
scene({ id: 'x-flood', dur: 9, act: 5, label: X5, mood: { dark: 1, blue: 1 }, sfx: [[0.3, 'rain', 0.8]],
  html: () => { const p = proj(FL.c, FL.k, FL.w, FL.h); const ar = road('Mirpur Road', FL.c, FL.k, FL.w, FL.h); const kn = road('Kazi Nazrul Avenue', FL.c, FL.k, FL.w, FL.h); const ap = road('Airport Road', FL.c, FL.k, FL.w, FL.h);
    const from = p(23.756, 90.375), to = p(23.729, 90.418);
    const bad = [from, p(23.746, 90.379), p(23.739, 90.383), p(23.733, 90.386), p(23.725, 90.396), p(23.72, 90.405), to];
    const good = [from, p(23.758, 90.39), p(23.7515, 90.3925), p(23.744, 90.395), p(23.7385, 90.3958), p(23.733, 90.403), p(23.73, 90.412), to];
    return panel('fm', 60, 200, FL.w, FL.h, dmap({ w: FL.w, h: FL.h, center: FL.c, k: FL.k, theme: 'light' }) +
      `<svg class="abs" viewBox="0 0 ${FL.w} ${FL.h}" style="inset:0">${[[23.739, 90.383], [23.725, 90.396]].map(([la, ln], i) => { const [x, y] = p(la, ln); return `<ellipse class="fz" cx="${x}" cy="${y}" rx="70" ry="44" fill="#3B82F6" opacity="0"/>`; }).join('')}
        <polyline id="rb" points="${polyStr(bad)}" fill="none" stroke="#EF4444" stroke-width="9" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="16 12"/>
        <polyline id="rg" points="${polyStr(good)}" fill="none" stroke="#0C684F" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/></svg>
      ${cnv('rain', FL.w, FL.h)}
      ${[[23.739, 90.383], [23.725, 90.396]].map(([la, ln], i) => { const [x, y] = p(la, ln); return `<div class="abs wr" style="left:${x - 70}px;top:${y - 96}px;opacity:0"><span class="chip" style="background:#1D4ED8;color:#fff">${icb('drop', 14, '#fff', 2.4)}Waterlogged · ${i ? 4 : 7} reports</span></div>`; }).join('')}
      <div class="card" id="fc" style="left:30px;top:${FL.h - 130}px;width:520px;padding:16px 20px;border-radius:18px;opacity:0"><div class="row" style="gap:12px"><div style="width:46px;height:46px;border-radius:14px;background:#DBEAFE;display:flex;align-items:center;justify-content:center">${icb('rain', 24, '#1D4ED8', 2.2)}</div><div><b style="font-size:18px">Route avoids 2 waterlogged roads</b><div style="font-size:14px;color:#5E6C65">Mirpur Road & Azimpur flooded · +3 min, never stuck</div></div></div></div>`); },
  update(lt, d, r) { panelIn($('#fm', r), lt, 0.1); animTB($('#t', r), lt, 0.4);
    const g = $('#rain', r).getContext('2d'); g.clearRect(0, 0, FL.w, FL.h); g.strokeStyle = 'rgba(30,64,175,.35)'; g.lineWidth = 1.6; const rr = srand(4); for (let i = 0; i < 260; i++) { const x = rr() * FL.w, sp = 600 + rr() * 500, y = ((rr() * FL.h + lt * sp) % (FL.h + 40)) - 20; g.beginPath(); g.moveTo(x, y); g.lineTo(x - 6, y + 22); g.stroke(); }
    $$('.fz', r).forEach((el, i) => el.setAttribute('opacity', P(lt, 1.0 + i * 0.4, 2.0 + i * 0.4) * (0.42 + 0.08 * Math.sin(lt * 3)))); $$('.wr', r).forEach((el, i) => { const k = P(lt, 2.0 + i * 0.4, 2.5 + i * 0.4, E.back); S(el, { s: Math.max(0, k), op: clamp(k * 2) }); });
    const rb = $('#rb', r); rb.style.opacity = 1 - P(lt, 4.0, 4.6) * 0.7; const rg = $('#rg', r); const len = rg.getTotalLength(); rg.style.strokeDasharray = len; rg.style.strokeDashoffset = len * (1 - P(lt, 3.6, 5.2, E.inOut)); const kc = P(lt, 5.2, 5.7, E.back); S($('#fc', r), { s: Math.max(0, kc), op: clamp(kc * 2) }); },
  caps: [[0.4, 4.0, 'Monsoon rain: when the fleet slows to a crawl and drivers tap “water here”, Cholo knows.'], [4.1, 8.7, 'Routes re-draw around waterlogged roads, so you arrive a little later — but never stuck.']] });
SCENES.at(-1).html = ((h) => () => h() + tb({ id: 't', num: '17', eyebrow: 'Flood-aware routing', hl: 'Monsoon?|@Route around it.', sub: 'Live flood layer from fleet speed, rainfall and one-tap driver reports.', x: 1300, y: 260, w: 560, tint: 'cyan', sm: true }))(SCENES.at(-1).html);

const MT = { c: [23.7985, 90.392], k: 4800, w: 900, h: 860 };
scene({ id: 'x-metro', dur: 14, act: 5, label: X5, mood: MD, sfx: [[5.2, 'metro'], [9.8, 'chime']],
  html: () => { const p = proj(MT.c, MT.k, MT.w, MT.h); const st = window.DHAKA.mrt.map(([n, la, ln]) => [n, ...p(la, ln)]);
    const home = p(23.874, 90.398), dest = p(23.733, 90.4205); const bike = [home, p(23.872, 90.385), p(23.8705, 90.372), [st[0][1], st[0][2]]]; const walk = [[st[15][1], st[15][2]], dest];
    return panel('mm', 60, 120, MT.w, MT.h, dmap({ w: MT.w, h: MT.h, center: MT.c, k: MT.k, theme: 'light', bld: false }) +
      `<svg class="abs" viewBox="0 0 ${MT.w} ${MT.h}" style="inset:0"><polyline points="${polyStr(st.map(([, x, y]) => [x, y]))}" fill="none" stroke="#E11D48" stroke-width="9" stroke-linecap="round" stroke-linejoin="round" opacity=".9"/>
        <polyline id="mtl" points="${polyStr(st.map(([, x, y]) => [x, y]))}" fill="none" stroke="#FFE58A" stroke-width="5" stroke-linecap="round" opacity=".9"/>
        ${st.map(([n, x, y], i) => `<circle class="ms" data-i="${i}" cx="${x}" cy="${y}" r="9" fill="#fff" stroke="#E11D48" stroke-width="4"/>`).join('')}
        <polyline id="bk" points="${polyStr(bike)}" fill="none" stroke="#0C684F" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>
        <polyline id="wk" points="${polyStr(walk)}" fill="none" stroke="#475569" stroke-width="6" stroke-dasharray="4 10" stroke-linecap="round"/>
        <circle cx="${home[0]}" cy="${home[1]}" r="12" fill="#0C684F" stroke="#fff" stroke-width="4"/><circle cx="${dest[0]}" cy="${dest[1]}" r="12" fill="#DC2626" stroke="#fff" stroke-width="4"/></svg>
      ${st.map(([n, x, y], i) => (i % 3 === 0 || i === 15 || i === 5) ? `<div class="abs msl" data-i="${i}" style="left:${x + 16}px;top:${y - 12}px;font-size:15px;font-weight:800;color:#9F1239;white-space:nowrap;text-shadow:0 0 4px #fff,0 0 4px #fff">${n}</div>` : '').join('')}
      <div class="abs" id="mv" style="left:0;top:0;width:44px;height:44px;margin:-22px 0 0 -22px;border-radius:50%;background:#0C684F;display:flex;align-items:center;justify-content:center;box-shadow:0 6px 16px rgba(0,0,0,.35)"><span id="mvi"></span></div>
      <div class="abs lbl" style="left:24px;bottom:20px;color:#9F1239">MRT Line 6 · Uttara North → Motijheel</div>`); },
  update(lt, d, r) {
    panelIn($('#mm', r), lt, 0.1); animTB($('#t', r), lt, 0.3);
    $$('.oc', r).forEach((el, i) => { const k = P(lt, 1.0 + i * 0.25, 1.6 + i * 0.25, E.back); S(el, { x: (1 - k) * 40, op: clamp(k * 2) }); const on = i === 1 && lt > 2.6; el.style.borderColor = on ? '#FBBF2E' : 'rgba(255,255,255,.16)'; el.style.background = on ? 'rgba(251,191,46,.14)' : 'rgba(255,255,255,.06)'; S(el, { s: on ? 1.03 : 1, x: (1 - k) * 40, op: clamp(k * 2) }); });
    const pts = (s) => $(s, r).getAttribute('points').split(' ').map((q) => q.split(',').map(Number));
    if (!r.__mp) r.__mp = { bk: pts('#bk'), mt: pts('#mtl'), wk: pts('#wk') };
    const kb = P(lt, 3.2, 5.2, E.inOut), km = P(lt, 5.3, 9.6, E.inOut), kw = P(lt, 9.7, 11.0, E.inOut);
    const bl = $('#bk', r), bLen = bl.getTotalLength(); bl.style.strokeDasharray = bLen; bl.style.strokeDashoffset = bLen * (1 - kb);
    const ml = $('#mtl', r), mLen = ml.getTotalLength(); ml.style.strokeDasharray = mLen; ml.style.strokeDashoffset = mLen * (1 - km);
    const wl = $('#wk', r); wl.style.opacity = kw > 0 ? 1 : 0;
    let pos, icon; if (lt < 5.25) { pos = along(r.__mp.bk, kb); icon = 'bike'; } else if (lt < 9.65) { pos = along(r.__mp.mt, km); icon = 'train'; } else { pos = along(r.__mp.wk, kw); icon = 'walk'; }
    const mv = $('#mv', r); S(mv, { x: pos[0] + 60 - 60, y: pos[1], op: P(lt, 3.0, 3.3) }); mv.style.left = '0px'; mv.style.background = icon === 'train' ? '#E11D48' : icon === 'walk' ? '#475569' : '#0C684F';
    if ($('#mvi', r).dataset.i !== icon) { $('#mvi', r).dataset.i = icon; $('#mvi', r).innerHTML = icb(icon, 24, '#fff', 2.4); }
    $$('.ms', r).forEach((c) => { const i = +c.dataset.i; const lit = km * 15 >= i - 0.01 && lt > 5.3; c.setAttribute('fill', lit ? '#FFE58A' : '#fff'); c.setAttribute('r', lit ? 10 : 8); });
    const legs = [['bike', 'Cholo Bike to Uttara North', '8 min', '৳45', 3.2], ['train', 'MRT Line 6 · 9 stations', '20 min', '৳90', 5.3], ['walk', 'Walk to Motijheel office', '2 min', '৳0', 9.7]];
    $$('.lg', r).forEach((el, i) => { const k = P(lt, legs[i][4], legs[i][4] + 0.5, E.back); S(el, { op: clamp(k * 2), x: (1 - k) * 30 }); });
    const tot = P(lt, 10.6, 12.0); $('#tt', r).textContent = `${Math.round(30 * tot)} min`; $('#tc', r).textContent = `৳${Math.round(135 * tot)}`; S($('#tot', r), { op: P(lt, 10.4, 10.8) });
    const kbtn = P(lt, 12.4, 12.9, E.back); S($('#bb', r), { op: clamp(kbtn * 2), s: (lt > 13.2 && lt < 13.45 ? 0.95 : 1) * Math.max(0, kbtn) }); },
  caps: [[0.4, 3.0, 'Uttara to Motijheel at rush hour. A car takes 55 minutes and ৳320.'], [3.1, 9.6, 'Cholo plans it smarter: a bike to Uttara North, then MRT Line 6 straight across the city.'], [9.7, 14.7, 'A short walk and you’re there — 25 minutes sooner, for less than half the price.']] });
SCENES.at(-1).html = ((h) => () => h() + `${tb({ id: 't', num: '18', eyebrow: 'Metro + Cholo', hl: 'Ride to the Metro.|~Beat the traffic.', x: 1020, y: 110, w: 860, sm: true })}
  <div class="abs" style="left:1020px;top:330px;width:840px">${[['car', 'Car all the way', '55 min', '৳320', ''], ['train', 'Bike + Metro + walk', '30 min', '৳135', 'FASTEST'], ['users', 'Bus + walk', '70 min', '৳40', '']].map(([i, n, tm, c, b]) => `<div class="oc row" style="gap:16px;padding:16px 20px;margin-bottom:10px;border-radius:18px;border:2px solid rgba(255,255,255,.16);background:rgba(255,255,255,.06)">
    <div style="width:46px;height:46px;border-radius:14px;background:${i === 'train' ? '#E11D48' : 'rgba(255,255,255,.12)'};display:flex;align-items:center;justify-content:center">${icb(i === 'car' ? 'nav' : i, 24, '#fff', 2.2)}</div>
    <div style="flex:1"><b style="font-size:22px">${n}</b>${b ? ` <span class="tag" style="background:#FBBF2E;color:#0E261F;margin-left:8px">${b}</span>` : ''}</div><div style="font-size:22px;font-weight:800;width:110px;text-align:right">${tm}</div><div style="font-size:22px;font-weight:800;width:90px;text-align:right" class="${b ? 'goldt' : ''}">${c}</div></div>`).join('')}</div>
  <div class="abs" style="left:1020px;top:640px;width:840px">${[['bike', 'Cholo Bike to Uttara North', '8 min', '৳45'], ['train', 'MRT Line 6 · 9 stations', '20 min', '৳90'], ['walk', 'Walk to Motijheel office', '2 min', '৳0']].map(([i, n, tm, c]) => `<div class="lg row" style="gap:12px;font-size:19px;font-weight:700;margin-bottom:8px;opacity:0">${icb(i, 22, '#FBBF2E', 2.2)}<span style="flex:1">${n}</span><span>${tm}</span><span style="width:70px;text-align:right">${c}</span></div>`).join('')}
    <div id="tot" class="row" style="gap:18px;margin-top:10px;padding-top:12px;border-top:1px solid rgba(255,255,255,.2);opacity:0"><span style="font-size:22px;font-weight:700;flex:1">Total</span><span id="tt" class="goldt" style="font-size:40px;font-weight:900">0 min</span><span id="tc" class="goldt" style="font-size:40px;font-weight:900">৳0</span></div>
    <div id="bb" class="btn" style="margin-top:14px;font-size:20px;padding:16px;opacity:0">Book the Cholo leg · Bike ৳45</div></div>`)(SCENES.at(-1).html);

scene({ id: 'x-bd', dur: 9, act: 5, label: X5, mood: MD,
  html: () => { const w = 400, h = 300; const night = dmap({ w, h, center: [23.79, 90.41], k: 30000, theme: 'dark', bld: false }); const sr = road('Gulshan Avenue', [23.79, 90.41], 30000, w, h);
    return `${head5('19', 'Made for Bangladesh', 'Problems global apps ignore.', 'Solved here.')}
    ${panel('b0', 110, 260, 410, 660, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Fair-fare meter</div><div style="font-size:19px;font-weight:700;margin-top:14px">Street CNG · Farmgate → Mohakhali</div>
      <div style="margin-top:40px;position:relative;height:60px"><div style="position:absolute;left:0;right:0;top:24px;height:12px;border-radius:6px;background:linear-gradient(90deg,#22C55E,#FBBF2E,#EF4444)"></div><div id="fr" style="position:absolute;left:30%;width:36%;top:14px;height:32px;border-radius:10px;border:3px solid #fff;background:rgba(255,255,255,.15)"></div><div id="fq" style="position:absolute;top:0;left:0;width:4px;height:60px;background:#fff;border-radius:2px"></div></div>
      <div class="row" style="justify-content:space-between;font-size:16px;color:rgba(255,255,255,.6);font-weight:700"><span>৳80</span><span>৳220</span></div>
      <div style="margin-top:24px;font-size:20px;font-weight:700">Fair price <span class="goldt" style="font-size:40px;font-weight:900">৳120–150</span></div>
      <div id="fq2" class="ucard" style="margin-top:20px;padding:14px;opacity:0"><b style="font-size:16px;color:#B91C1C">Driver asked ৳200</b><div style="font-size:13px;color:#5E6C65">That’s 33% above the fair range · share this card</div></div></div>`)}
    ${panel('b1', 550, 260, 410, 660, `<div style="padding:24px"><div class="lbl" style="color:#F9A8D4">Women-safe night mode</div><div style="margin-top:14px;position:relative;width:${w - 40}px;height:${h}px;border-radius:16px;overflow:hidden">${night}
      <svg class="abs" viewBox="0 0 ${w} ${h}" style="inset:0"><polyline id="ws" points="${polyStr(sr)}" fill="none" stroke="#F472B6" stroke-width="8" stroke-linecap="round" filter="drop-shadow(0 0 8px #F472B6)"/></svg></div>
      ${['Woman driver · Nusrat J. ★4.9', 'Trip shared with Ammu automatically', 'Well-lit, busy roads after 9 PM'].map((x) => `<div class="wsl row" style="gap:10px;margin-top:14px;font-size:17px;font-weight:700;opacity:0">${icb('check', 18, '#F9A8D4', 3)}${x}</div>`).join('')}</div>`)}
    ${panel('b2', 990, 260, 410, 660, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Festival & Eid mode</div><div style="margin-top:16px">${icb('moon', 64, '#FBBF2E', 1.8)}</div>
      <div class="ucard" style="margin-top:10px;padding:16px"><div style="font-size:13px;color:#5E6C65;font-weight:800;letter-spacing:2px">INTERCITY · EID-UL-ADHA</div><div style="font-size:22px;font-weight:900;margin-top:6px">Dhaka → Rajshahi</div><div class="row" style="justify-content:space-between;margin-top:8px;font-size:15px;font-weight:700"><span>Car · 5 h 40 m</span><span style="color:#0C684F">৳4,800</span></div></div>
      <div id="eid" style="margin-top:16px;font-size:17px;line-height:1.6;color:rgba(255,255,255,.8);font-weight:600;opacity:0">Extra drivers positioned at bus terminals<br>Event-aware ETAs for exodus traffic</div></div>`)}
    ${panel('b3', 1430, 260, 410, 660, `<div style="padding:24px"><div class="row" style="justify-content:space-between"><div class="lbl" style="color:#67E8F9">Lite mode</div><span class="row" style="gap:6px;font-weight:800;color:#FBBF2E">${icb('signal', 18, '#FBBF2E', 2.4)}2G</span></div>
      <div style="margin-top:16px;background:#F8FAF5;color:#111;border-radius:14px;padding:16px;font-family:monospace;font-size:15px;line-height:1.7"><b>CHOLO LITE</b><br>From: Road 23, Dhanmondi<br>To: <span id="lt"></span><br>CNG ৳182 · 19 min<br><span id="lb" style="opacity:0;background:#0C684F;color:#fff;padding:2px 8px;border-radius:6px">[ BOOK ]</span></div>
      <div id="lsz" style="margin-top:18px;font-size:17px;font-weight:700;color:rgba(255,255,255,.8);opacity:0">Loads in 1.8 s on 2G · 14 KB</div></div>`)}`; },
  caps: [[0.4, 3.4, 'A fair-fare meter for street CNGs. Women-safe night routes with women drivers.'], [3.5, 9.2, 'Eid mode for the exodus, and a Lite mode that books a ride over a 2G connection.']],
  update(lt, d, r) { headIn(r, lt); [0, 1, 2, 3].forEach((i) => panelIn($('#b' + i, r), lt, 0.2 + i * 0.12));
    S($('#fq', r), { x: L(0, 330, P(lt, 1.0, 2.0, E.out)) * 0.86 }); S($('#fq2', r), { op: P(lt, 2.2, 2.6) });
    const ws = $('#ws', r); const len = ws.getTotalLength(); ws.style.strokeDasharray = len; ws.style.strokeDashoffset = len * (1 - P(lt, 1.2, 2.8, E.inOut)); $$('.wsl', r).forEach((el, i) => S(el, { op: P(lt, 2.2 + i * 0.3, 2.6 + i * 0.3) }));
    S($('#eid', r), { op: P(lt, 3.6, 4.0) }); typeText($('#lt', r), 'Gulshan 2 Circle', lt, 4.0, 14); S($('#lb', r), { op: P(lt, 5.4, 5.6) }); S($('#lsz', r), { op: P(lt, 5.8, 6.2) }); } });

scene({ id: 'x-safety', dur: 8.5, act: 5, label: X5, mood: { dark: 1, red: 0.5 }, sfx: [[3.2, 'alert2'], [6.0, 'alarm', 0.6]],
  html: () => `${head5('20', 'Safety AI', 'Something wrong?', 'Cholo notices first.')}
    ${panel('a1', 110, 260, 840, 660, `<div style="padding:24px"><div class="lbl" style="color:#FCA5A5">Trip anomaly detection</div><svg viewBox="0 0 790 420" style="width:790px;height:420px;margin-top:10px"><path d="M40 360 C 200 330, 300 230, 420 200 S 640 110, 760 60" fill="none" stroke="rgba(34,197,94,.25)" stroke-width="70" stroke-linecap="round"/><path d="M40 360 C 200 330, 300 230, 420 200 S 640 110, 760 60" fill="none" stroke="#22C55E" stroke-width="4" stroke-dasharray="10 10"/>
      <path id="tr" d="M40 360 C 200 330, 300 230, 400 210 S 470 330, 520 380" fill="none" stroke="#EF4444" stroke-width="7" stroke-linecap="round"/></svg>
      <div class="card" id="ok" style="left:430px;top:110px;width:370px;padding:16px 18px;border-radius:18px;opacity:0"><b style="font-size:19px">Are you okay?</b><div style="font-size:14px;color:#5E6C65;margin-top:2px">Your car left the planned route.</div><div class="row" style="gap:8px;margin-top:10px"><span class="chip" style="background:#EAF4EE;color:#0C684F">I’m fine</span><span class="chip" style="background:#FEE2E2;color:#B91C1C">Get help</span></div></div>
      <div id="esc" class="row" style="gap:10px;font-size:19px;font-weight:800;color:#FCA5A5;opacity:0;margin-top:-30px">${icb('alert', 22, '#FCA5A5', 2.4)}No reply in 60 s → SOS board + trusted contacts</div></div>`)}
    ${panel('a2', 990, 260, 820, 660, `<div style="padding:24px"><div class="lbl" style="color:#FCA5A5">Crash detection</div><svg viewBox="0 0 770 260" style="width:770px;height:260px;margin-top:10px"><polyline id="acc" points="${[...Array(120)].map((_, i) => `${i * 6.4},${130 + (i > 62 && i < 70 ? (i % 2 ? -110 : 110) : Math.sin(i * 0.9) * 10 * (i < 70 ? 1 : 0.15))}`).join(' ')}" fill="none" stroke="#F87171" stroke-width="3"/></svg>
      <div class="row" style="gap:30px;margin-top:10px;align-items:center"><div style="position:relative;width:180px;height:180px"><svg viewBox="0 0 100 100" style="width:180px;height:180px;transform:rotate(-90deg)"><circle cx="50" cy="50" r="44" fill="none" stroke="rgba(255,255,255,.12)" stroke-width="8"/><circle id="cdr" cx="50" cy="50" r="44" fill="none" stroke="#EF4444" stroke-width="8" stroke-dasharray="276.5" stroke-linecap="round"/></svg><div id="cdn" class="abs" style="inset:0;display:flex;align-items:center;justify-content:center;font-size:64px;font-weight:900">10</div></div>
      <div><b style="font-size:26px">Possible crash detected</b><div style="font-size:18px;color:rgba(255,255,255,.7);margin-top:6px">Calling Cholo support in <span id="cds">10</span> s<br>then emergency services</div><div class="chip" style="margin-top:14px;background:#fff;color:#B91C1C">I’m okay — cancel</div></div></div></div>`)}`,
  caps: [[0.4, 4.4, 'If a car leaves its route or stops for too long, Cholo checks in. No answer? It escalates.'], [4.5, 8.7, 'A sudden crash shows up in the phone’s motion sensors — help is called automatically.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#a1', r), lt, 0.2); panelIn($('#a2', r), lt, 0.35);
    const tr = $('#tr', r); const len = tr.getTotalLength(); tr.style.strokeDasharray = len; tr.style.strokeDashoffset = len * (1 - P(lt, 0.8, 3.0, E.inOut)); const ko = P(lt, 3.1, 3.6, E.back); S($('#ok', r), { s: Math.max(0, ko), op: clamp(ko * 2) }); S($('#esc', r), { op: P(lt, 4.0, 4.4) });
    const ac = $('#acc', r); const al = ac.getTotalLength(); ac.style.strokeDasharray = al; ac.style.strokeDashoffset = al * (1 - P(lt, 4.4, 6.0, E.lin)); const c = clamp(lt - 6.0, 0, 10); const n = Math.max(0, 10 - Math.floor(c * 3)); $('#cdn', r).textContent = n; $('#cds', r).textContent = n; $('#cdr', r).style.strokeDashoffset = 276.5 * (1 - n / 10); } });

scene({ id: 'x-driverai', dur: 8.5, act: 5, label: X5, mood: MD,
  html: `${head5('21', 'Driver safety', 'Alert drivers.', 'Real drivers. Safer roads.')}
    ${panel('f1', 110, 260, 540, 640, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Drowsiness detection</div><svg viewBox="0 0 200 220" style="width:300px;height:330px;display:block;margin:16px auto 0"><ellipse cx="100" cy="110" rx="70" ry="92" fill="none" stroke="#67E8F9" stroke-width="1.5" opacity=".6"/>${[...Array(46)].map((_, i) => { const a = i / 46 * 6.28, rr = 0.55 + ((i * 37) % 10) / 22; return `<circle cx="${(100 + Math.cos(a) * 62 * rr).toFixed(1)}" cy="${(110 + Math.sin(a) * 84 * rr).toFixed(1)}" r="1.6" fill="#67E8F9" opacity=".8"/>`; }).join('')}
      <ellipse class="eye" cx="72" cy="92" rx="16" ry="8" fill="none" stroke="#FBBF2E" stroke-width="3"/><ellipse class="eye" cx="128" cy="92" rx="16" ry="8" fill="none" stroke="#FBBF2E" stroke-width="3"/><path d="M80 160 Q100 172 120 160" fill="none" stroke="#67E8F9" stroke-width="2"/></svg>
      <div id="dz" class="card" style="position:relative;margin-top:10px;padding:12px 16px;opacity:0"><b>Take a 15-minute break</b><div style="font-size:13px;color:#5E6C65">You’ve driven 6 h 10 m · eyes closing often</div></div>
      <div class="row" style="gap:8px;margin-top:12px;font-size:14px;font-weight:800;color:#67E8F9">${icb('lock', 16, '#67E8F9', 2.4)}On-device · never uploaded</div></div>`)}
    ${panel('f2', 690, 260, 540, 640, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Selfie liveness check</div><div style="margin:20px auto 0;width:300px;height:300px;border-radius:50%;border:6px solid #22D3EE;position:relative;overflow:hidden;background:linear-gradient(180deg,#24414A,#132A30)" id="lv"><svg viewBox="0 0 200 200" style="position:absolute;inset:0"><circle cx="100" cy="86" r="42" fill="#C08B62"/><path d="M40 200 Q100 120 160 200" fill="#0C684F"/><ellipse class="eye2" cx="84" cy="82" rx="6" ry="4" fill="#1F2937"/><ellipse class="eye2" cx="116" cy="82" rx="6" ry="4" fill="#1F2937"/></svg></div>
      <div id="lvp" style="text-align:center;margin-top:20px;font-size:26px;font-weight:900">Blink</div><div id="lvd" class="row" style="justify-content:center;gap:10px;margin-top:12px;font-size:19px;font-weight:800;color:#86EFAC;opacity:0">${icb('check', 22, '#86EFAC', 3)}Identity verified · Rahim H.</div></div>`)}
    ${panel('f3', 1270, 260, 540, 640, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Driver behaviour score</div><div style="position:relative;width:300px;height:170px;margin:30px auto 0"><svg viewBox="0 0 200 110" style="width:300px;height:165px"><path d="M15 100 A85 85 0 0 1 185 100" fill="none" stroke="rgba(255,255,255,.12)" stroke-width="16" stroke-linecap="round"/><path id="gs" d="M15 100 A85 85 0 0 1 185 100" fill="none" stroke="url(#gg)" stroke-width="16" stroke-linecap="round"/><defs><linearGradient id="gg"><stop offset="0" stop-color="#22D3EE"/><stop offset="1" stop-color="#FBBF2E"/></linearGradient></defs></svg><div id="gsv" class="abs" style="left:0;right:0;top:70px;text-align:center;font-size:64px;font-weight:900">0</div></div>
      ${[['Smooth braking', '98'], ['Speed limits', '94'], ['Phone-free driving', '89']].map(([n, v]) => `<div class="bs row" style="justify-content:space-between;margin-top:14px;font-size:19px;font-weight:700;opacity:0"><span>${n}</span><span class="goldt">${v}</span></div>`).join('')}
      <div id="bb2" class="chip" style="margin-top:18px;background:#FBBF2E;color:#0E261F;opacity:0">${icb('star', 16, '#0E261F', 2.4)} Top 5% this week · insurance discount</div></div>`)}`,
  caps: [[0.4, 3.0, 'An on-device camera model spots tired eyes and tells the driver to rest.'], [3.1, 5.7, 'A selfie liveness check at every shift stops account sharing.'], [5.8, 8.2, 'And a weekly driving score rewards the safest drivers.']],
  update(lt, d, r) { headIn(r, lt); [1, 2, 3].forEach((i) => panelIn($('#f' + i, r), lt, 0.1 + i * 0.12));
    const blink = lt > 1.0 && lt < 2.6 ? Math.abs(Math.sin(lt * 4)) : 1; $$('.eye', r).forEach((e) => e.setAttribute('ry', (8 * blink).toFixed(1))); S($('#dz', r), { op: P(lt, 2.2, 2.6) });
    const b2 = lt > 3.6 && lt < 4.0 ? 0.1 : 1; $$('.eye2', r).forEach((e) => e.setAttribute('ry', (4 * b2).toFixed(1))); $('#lvp', r).textContent = lt < 4.0 ? 'Blink' : lt < 5.0 ? 'Turn your head' : 'Done'; S($('#lv', r), { r: lt > 4.0 && lt < 5.0 ? Math.sin((lt - 4) * 6) * 12 : 0 }); S($('#lvd', r), { op: P(lt, 5.0, 5.4) });
    const gs = $('#gs', r); const gl = gs.getTotalLength(); gs.style.strokeDasharray = gl; const kg = P(lt, 5.8, 7.2, E.out); gs.style.strokeDashoffset = gl * (1 - 0.92 * kg); $('#gsv', r).textContent = Math.round(92 * kg); $$('.bs', r).forEach((el, i) => S(el, { op: P(lt, 6.4 + i * 0.2, 6.8 + i * 0.2) })); S($('#bb2', r), { op: P(lt, 7.4, 7.8) }); } });

scene({ id: 'x-fraud', dur: 8, act: 5, label: X5, mood: { dark: 1, red: 0.3 },
  html: () => { const rr = srand(17); const N = [...Array(34)].map((_, i) => ({ x: 120 + rr() * 820, y: 80 + rr() * 460, k: ['user', 'phone', 'wallet'][i % 3], bad: i < 7 })); N.slice(0, 7).forEach((n, i) => { n.x = 640 + Math.cos(i) * 110; n.y = 300 + Math.sin(i * 1.3) * 90; });
    const E2 = []; for (let i = 0; i < 7; i++) for (let j = i + 1; j < 7; j++) if ((i + j) % 2) E2.push([i, j, 1]); for (let i = 7; i < 34; i++) E2.push([i, 7 + Math.floor(rr() * 27), 0]);
    return `${head5('22', 'Fraud defence', 'Fake trips, fake GPS.', 'Caught before they cost you.')}
    ${panel('g1', 110, 260, 1060, 660, `<svg viewBox="0 0 1060 620" style="width:1060px;height:620px">${E2.map(([a, b, bad]) => `<line class="ge ${bad ? 'bad' : ''}" x1="${N[a].x}" y1="${N[a].y}" x2="${N[b].x}" y2="${N[b].y}" stroke="${bad ? '#EF4444' : 'rgba(103,232,249,.25)'}" stroke-width="${bad ? 3 : 1.5}" opacity="0"/>`).join('')}
      ${N.map((n, i) => `<g class="gn ${n.bad ? 'bad' : ''}" transform="translate(${n.x},${n.y})" opacity="0"><circle r="${n.bad ? 18 : 13}" fill="${n.bad ? '#7F1D1D' : '#0E3440'}" stroke="${n.bad ? '#F87171' : '#67E8F9'}" stroke-width="2.5"/><g transform="translate(-9,-9) scale(.75)" stroke="${n.bad ? '#FCA5A5' : '#67E8F9'}" fill="none" stroke-width="2.4">${I[n.k]}</g></g>`).join('')}</svg>
      <div class="abs lbl" style="left:24px;top:20px;color:#67E8F9">Users · devices · wallets</div><div id="cl" class="card" style="left:760px;top:470px;width:270px;padding:12px 16px;border-radius:16px;opacity:0"><b style="color:#B91C1C">Promo-farming ring</b><div style="font-size:13px;color:#5E6C65">7 accounts · 2 phones · 1 wallet</div></div>`)}
    <div class="glassc" id="g2" style="left:1210px;top:260px;width:600px;height:660px;padding:26px"><div class="lbl" style="color:#FCA5A5">Risk score · trip JT-2026-000802</div><div id="rs" class="redt" style="font-size:110px;font-weight:900;line-height:1.1">0</div>
      ${['GPS jumped 14 km in 3 s (spoofing)', 'Same device as 6 other accounts', 'Promo used 7 times on one route', 'Human review before any ban'].map((x, i) => `<div class="rf row" style="gap:12px;margin-top:14px;font-size:19px;font-weight:700;opacity:0">${icb(i === 3 ? 'user' : 'flag', 20, i === 3 ? '#67E8F9' : '#F87171', 2.4)}${x}</div>`).join('')}</div>`; },
  caps: [[0.4, 7.7, 'A graph of users, devices and wallets exposes fake-trip rings and spoofed GPS — every flag reviewed by a person.']],
  update(lt, d, r) { headIn(r, lt); panelIn($('#g1', r), lt, 0.2); panelIn($('#g2', r), lt, 0.35);
    $$('.gn', r).forEach((g, i) => g.setAttribute('opacity', P(lt, 0.5 + i * 0.03, 0.9 + i * 0.03))); $$('.ge', r).forEach((g, i) => { const bad = g.classList.contains('bad'); g.setAttribute('opacity', bad ? P(lt, 2.4, 3.0) * (0.6 + 0.4 * Math.sin(lt * 6)) : P(lt, 0.8, 1.6) * 0.8); });
    const kc = P(lt, 3.0, 3.5, E.back); S($('#cl', r), { s: Math.max(0, kc), op: clamp(kc * 2) }); $('#rs', r).textContent = Math.round(87 * P(lt, 1.5, 3.5)); $$('.rf', r).forEach((el, i) => S(el, { op: P(lt, 3.6 + i * 0.4, 4.0 + i * 0.4), x: (1 - P(lt, 3.6 + i * 0.4, 4.0 + i * 0.4)) * 20 })); } });

const DT = [['trend', 'Earnings forecast', 'Drive 5–9 PM in Gulshan', '৳1,400–1,800'], ['cal', 'AI shift planner', 'Goal ৳20,000 this week', '5 shifts planned'], ['fuel', 'True profit', 'Fares − CNG − maintenance', '৳3,940 kept'], ['battery', 'EV calculator', 'Electric bike on your trips', 'Pays off in 11 mo'], ['camera', 'NID & licence OCR', 'Photo fills the form', 'Done in 20 s'], ['shield', 'Fair deactivation', 'Every reason shown', 'Human appeal']];
scene({ id: 'x-drv', dur: 8, act: 5, label: X5, mood: MD,
  html: `${head5('23', 'AI for drivers', 'Plan the week.', 'Keep more of every taka.')}
    <div class="abs" style="left:110px;top:270px;width:1700px;display:grid;grid-template-columns:repeat(3,1fr);gap:24px">${DT.map(([i, t, s, v]) => `<div class="glassc dt" style="position:relative;padding:26px 28px;height:300px"><div style="width:58px;height:58px;border-radius:18px;background:rgba(34,211,238,.15);display:flex;align-items:center;justify-content:center">${icb(i, 30, '#67E8F9', 2)}</div>
      <div style="font-size:28px;font-weight:800;margin-top:18px">${t}</div><div style="font-size:19px;color:rgba(255,255,255,.65);margin-top:6px;font-weight:500">${s}</div><div class="goldt dv" style="font-size:36px;font-weight:900;margin-top:16px">${v}</div></div>`).join('')}</div>`,
  caps: [[0.4, 7.7, 'Earnings forecasts, a shift planner, true profit after fuel, an EV calculator, instant document scanning — and fair, explained decisions.']],
  update(lt, d, r) { headIn(r, lt); $$('.dt', r).forEach((el, i) => { const k = P(lt, 0.4 + i * 0.14, 1.1 + i * 0.14, E.back); S(el, { y: (1 - k) * 50, s: L(0.9, 1, Math.max(0, k)), op: clamp(k * 2) }); S($('.dv', el), { op: P(lt, 1.3 + i * 0.14, 1.8 + i * 0.14) }); }); } });

scene({ id: 'x-delight', dur: 8.5, act: 5, label: X5, mood: MD,
  html: `${head5('24', 'Delightful by design', 'Every ride,', 'a little memorable.')}
    ${panel('d1', 110, 260, 540, 650, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Trip recap</div><svg viewBox="0 0 490 260" style="width:490px;height:260px;margin-top:10px"><path id="rcp" d="M40 220 C 120 200, 160 120, 240 120 S 380 60, 450 40" fill="none" stroke="#FBBF2E" stroke-width="8" stroke-linecap="round"/><circle id="rcc" r="10" fill="#fff"/></svg>
      <div class="row" style="justify-content:space-between;margin-top:6px">${[['7.2', 'km'], ['19', 'min'], ['0.9', 'kg CO₂ saved']].map(([v, u]) => `<div><div style="font-size:38px;font-weight:900">${v}</div><div style="font-size:15px;color:rgba(255,255,255,.6);font-weight:600">${u}</div></div>`).join('')}</div><div class="btn" style="margin-top:22px">Share my ride card</div></div>`)}
    ${panel('d2', 690, 260, 540, 650, `<div style="padding:30px;height:100%;background:linear-gradient(160deg,rgba(240,80,140,.25),rgba(34,211,238,.15))"><div class="lbl" style="color:#F9A8D4">Cholo Wrapped 2026</div><div style="font-size:30px;font-weight:800;margin-top:20px">Nusrat, this year you rode</div><div id="wk" class="goldt" style="font-size:110px;font-weight:900;line-height:1.05">0</div><div style="font-size:26px;font-weight:700">kilometres across Dhaka</div>
      <div style="margin-top:30px;font-size:21px;line-height:1.6;font-weight:600;color:rgba(255,255,255,.85)">Favourite place · Gulshan 2<br>Hours saved by Metro · 41<br>Top driver · Rahim ★4.9</div></div>`)}
    ${panel('d3', 1270, 260, 540, 650, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Lock-screen live trip</div><div style="margin-top:16px;border-radius:26px;background:linear-gradient(180deg,#1C2B26,#0E1714);padding:22px"><div style="font-size:56px;font-weight:200">9:41</div>
      <div style="margin-top:20px;background:rgba(255,255,255,.12);border-radius:20px;padding:16px"><div class="row" style="justify-content:space-between"><img src="logo-light.svg" style="height:20px"><b id="lse">3 min</b></div><div style="height:8px;border-radius:4px;background:rgba(255,255,255,.15);margin-top:12px"><div id="lsb" style="height:100%;width:0;border-radius:4px;background:#FBBF2E"></div></div><div style="font-size:14px;margin-top:8px;opacity:.75">Rahim · Green CNG · Tha 11-2345</div></div></div>
      <div class="row" style="gap:8px;margin-top:20px;flex-wrap:wrap">${['Screen reader', 'Voice-only mode', 'Large text', 'Colour-blind maps'].map((x) => `<span class="chip ac2" style="background:rgba(255,255,255,.1);color:#fff;font-size:15px;opacity:0">${icb('a11y', 14, '#67E8F9', 2.4)}${x}</span>`).join('')}</div></div>`)}`,
  caps: [[0.4, 8.2, 'Animated trip recaps, a yearly Cholo Wrapped, live lock-screen progress — and accessibility built in from day one.']],
  update(lt, d, r) { headIn(r, lt); [1, 2, 3].forEach((i) => panelIn($('#d' + i, r), lt, 0.1 + i * 0.12));
    const rc = $('#rcp', r); const len = rc.getTotalLength(); const k = P(lt, 0.8, 3.0, E.inOut); rc.style.strokeDasharray = len; rc.style.strokeDashoffset = len * (1 - k); const pt = rc.getPointAtLength(len * k); $('#rcc', r).setAttribute('cx', pt.x); $('#rcc', r).setAttribute('cy', pt.y);
    $('#wk', r).textContent = fmt(Math.round(1284 * P(lt, 1.6, 4.0))); const kl = P(lt, 2.0, 6.5, E.lin); $('#lsb', r).style.width = `${kl * 100}%`; $('#lse', r).textContent = `${Math.max(1, 3 - Math.floor(kl * 3))} min`; $$('.ac2', r).forEach((el, i) => S(el, { op: P(lt, 4.4 + i * 0.25, 4.8 + i * 0.25) })); } });

scene({ id: 'x-scale', dur: 8.5, act: 5, label: X5, mood: MD,
  html: `${head5('25', 'Built for scale', 'Ten thousand drivers.', 'Milliseconds to match.')}
    <div class="abs" style="left:110px;top:270px;width:1700px;display:grid;grid-template-columns:repeat(4,1fr);gap:22px">${[['Drivers online', 10000, ''], ['GPS pings / minute', 2400000, ''], ['p99 match time', 2.1, ' s'], ['Uptime', 99.98, '%']].map(([l, v, u]) => `<div class="glassc kw" style="position:relative;padding:24px 26px;height:190px"><div class="lbl" style="color:#67E8F9">${l}</div><div class="kv cyant" data-v="${v}" data-u="${u}" style="font-size:56px;font-weight:900;margin-top:16px;font-variant-numeric:tabular-nums">0</div></div>`).join('')}</div>
    ${panel('sp2', 110, 490, 830, 420, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Live event stream</div>${cnv('ev', 780, 320, 'top:70px;left:24px')}</div>`)}
    ${panel('ins', 980, 490, 830, 420, `<div style="padding:24px"><div class="lbl" style="color:#67E8F9">Dhaka Mobility Insights · public & anonymised</div><div style="font-size:26px;font-weight:800;margin-top:14px">Average speed on Mirpur Road this monsoon</div><div class="row" style="gap:20px;margin-top:10px;align-items:flex-end;height:200px">${[22, 21, 20, 18, 16, 15, 14, 18].map((v, i) => `<div class="ib" style="flex:1;height:${v * 8}px;border-radius:8px 8px 2px 2px;background:${i > 3 && i < 7 ? 'linear-gradient(180deg,#60A5FA,#1D4ED8)' : 'rgba(255,255,255,.2)'};transform-origin:50% 100%"></div>`).join('')}</div><div class="redt" style="font-size:44px;font-weight:900;margin-top:8px">−18%</div></div>`)}`,
  caps: [[0.4, 8.2, 'Streaming every ping, matching in about two seconds — and sharing anonymised insights with the city.']],
  update(lt, d, r) { headIn(r, lt); $$('.kw', r).forEach((el, i) => { const k = P(lt, 0.3 + i * 0.12, 0.9 + i * 0.12, E.back); S(el, { y: (1 - k) * 30, op: clamp(k * 2) }); const kv = $('.kv', el); const v = +kv.dataset.v * P(lt, 0.6 + i * 0.12, 2.6 + i * 0.12); kv.textContent = (+kv.dataset.v < 100 ? v.toFixed(+kv.dataset.v < 10 ? 1 : 2) : fmt(Math.round(v))) + kv.dataset.u; });
    panelIn($('#sp2', r), lt, 0.6); panelIn($('#ins', r), lt, 0.75);
    const g = $('#ev', r).getContext('2d'); g.clearRect(0, 0, 780, 320); for (let lane = 0; lane < 6; lane++) { g.fillStyle = 'rgba(255,255,255,.05)'; g.fillRect(0, lane * 52 + 10, 780, 34); const rr = srand(lane + 3); for (let k = 0; k < 18; k++) { const x = ((rr() * 780 + lt * (180 + lane * 40)) % 820) - 20; g.fillStyle = ['#67E8F9', '#FBBF2E', '#86EFAC', '#F9A8D4', '#67E8F9', '#FDE68A'][lane]; g.fillRect(x, lane * 52 + 18, 20, 18); } }
    $$('.ib', r).forEach((el, i) => { const k = P(lt, 1.4 + i * 0.1, 1.9 + i * 0.1, E.back); el.style.transform = `scaleY(${Math.max(0, k)})`; }); } });

const SUPER = [['pkg', 'Cholo Send', 'Parcels across the city'], ['gift', 'Food & grocery', 'Same dispatch engine'], ['plane', 'Airport transfers', 'Flight-aware pickups'], ['brief', 'Cholo for Business', 'Company rides & billing'], ['tag', 'Rewards & referrals', '৳50 for every friend'], ['zap', 'EV fleet', 'Charge-aware dispatch'], ['leaf', 'Carbon credits', 'From pooling & EVs'], ['headset', '24/7 support', 'Real people, any hour']];
scene({ id: 'x-super', dur: 7, act: 5, label: X5, mood: MD,
  html: `${head5('26', 'One super-app', 'Rides today.', 'Everything that moves, tomorrow.')}
    <div class="abs" style="left:110px;top:270px;width:1700px;display:grid;grid-template-columns:repeat(4,1fr);gap:22px">${SUPER.map(([i, t, s]) => `<div class="glassc su" style="position:relative;padding:24px 26px;height:250px"><div style="width:62px;height:62px;border-radius:18px;background:rgba(251,191,46,.16);display:flex;align-items:center;justify-content:center">${icb(i, 32, '#FBBF2E', 2)}</div><div style="font-size:27px;font-weight:800;margin-top:20px">${t}</div><div style="font-size:18px;color:rgba(255,255,255,.65);margin-top:6px;font-weight:500">${s}</div></div>`).join('')}</div>`,
  caps: [[0.4, 6.7, 'Parcels, food, airport rides, business accounts, rewards, electric fleets — one platform for everything that moves.']],
  update(lt, d, r) { headIn(r, lt); $$('.su', r).forEach((el, i) => { const dl = 0.4 + ((i % 4) + Math.floor(i / 4)) * 0.13; const k = P(lt, dl, dl + 0.6, E.back); S(el, { s: L(0.6, 1, Math.max(0, k)), op: clamp(k * 2), y: (1 - k) * 30 }); }); } });
