actCard('card6', '06', 'Why চলো', 'And so much more', { label: '06 · Why চলো' });
const W6 = '06 · Why চলো';
const MORE = [['pin', 'Live address search'], ['receipt', 'Upfront fares'], ['users', 'Women riders only'], ['shield', 'Confirmed pickup'], ['alert', 'One-tap SOS'], ['share', 'Live trip sharing'], ['wallet', 'Wallet & bKash'], ['cal', 'Scheduled rides'], ['tag', 'Promo codes'], ['heart', 'Favourite drivers'], ['globe', 'Bangla & English'], ['phone', 'SOS auto-call 999'], ['trend', 'Driver earnings'], ['map', 'Zones & surge'], ['db', 'Admin analytics'], ['train', 'Metro + ride']];
scene({ id: 'more', dur: 7.5, act: 6, label: W6,
  html: `<div class="center" id="mt" style="top:90px;font-size:84px;font-weight:900;letter-spacing:-3px">And <span class="goldt">so much more.</span></div>
    <div class="abs" style="left:160px;top:270px;width:1600px;display:grid;grid-template-columns:repeat(4,1fr);gap:20px">${MORE.map(([i, n]) => `<div class="glass ft" style="position:relative;padding:22px 24px;height:150px;border-radius:24px;display:flex;flex-direction:column;justify-content:space-between"><div style="width:52px;height:52px;border-radius:16px;background:rgba(251,191,46,.16);display:flex;align-items:center;justify-content:center">${icb(i, 28, '#FBBF2E', 2)}</div><div style="font-size:25px;font-weight:700">${n}</div></div>`).join('')}</div>`,
  caps: [[0.4, 7.2, 'Everything a city needs to move — in one app.']],
  update(lt, d, r) { const b = P(lt, 0.1, 0.8, E.out5); S($('#mt', r), { y: (1 - b) * 40, op: b }); $$('.ft', r).forEach((el, i) => { const dl = 0.4 + ((i % 4) + Math.floor(i / 4)) * 0.11; const k = P(lt, dl, dl + 0.55, E.back); S(el, { s: L(0.5, 1, Math.max(0, k)), op: clamp(k * 2), y: (1 - k) * 30 }); }); } });
scene({ id: 'outro', dur: 9, act: 6, label: '', noWm: true, sfx: [[0.1, 'impact'], [0.6, 'bells'], [8.6, 'hit']],
  html: `<div class="abs" id="o1" style="left:610px;top:180px;width:700px;height:330px"><img src="logo-light.svg" style="width:700px;display:block;filter:drop-shadow(0 30px 60px rgba(0,0,0,.5))">
      <div id="o1s" class="abs" style="inset:0;-webkit-mask:url(logo-light.svg) center/100% 100% no-repeat;mask:url(logo-light.svg) center/100% 100% no-repeat;background:linear-gradient(105deg,transparent 40%,rgba(255,255,255,.95) 50%,transparent 60%);background-size:300% 100%"></div></div>
    <div class="center" id="o2" style="top:560px;font-size:84px;font-weight:900;letter-spacing:-2px">Let’s go. <span class="goldt bnd" style="font-weight:800;letter-spacing:0">চলো!</span></div>
    <div class="center" id="o3" style="top:690px;font-size:28px;font-weight:600;letter-spacing:6px;color:rgba(255,255,255,.72)">RIDE SAFE &nbsp;·&nbsp; PAY EASY &nbsp;·&nbsp; EARN MORE</div>
    <div class="abs row" id="o4" style="left:0;right:0;top:780px;justify-content:center;gap:22px">
      <div style="padding:18px 32px;border-radius:20px;background:#fff;color:#0E261F;font-size:24px;font-weight:800">Available on Android</div><div style="padding:18px 32px;border-radius:20px;background:#fff;color:#0E261F;font-size:24px;font-weight:800">Available on iOS</div>
      <div style="padding:18px 32px;border-radius:20px;border:2px solid rgba(251,191,46,.7);color:#FFE58A;font-size:24px;font-weight:800">cholo-cholo7.vercel.app</div></div>`,
  update(lt, d, r) { const k = P(lt, 0.2, 1.4, E.out5); const o = $('#o1', r); o.style.filter = `blur(${(1 - k) * 16}px)`; S(o, { s: L(1.3, 1, k), op: clamp(k * 1.5) }); $('#o1s', r).style.backgroundPosition = `${L(120, -60, P(lt, 1.4, 2.6, E.inOut))}% 0`;
    const a = P(lt, 1.2, 2.0, E.out5); S($('#o2', r), { y: (1 - a) * 40, op: a }); const b = P(lt, 1.7, 2.4); S($('#o3', r), { y: (1 - b) * 24, op: b }); $('#o3', r).style.letterSpacing = `${L(16, 6, b)}px`; const c = P(lt, 2.2, 2.9, E.out5); S($('#o4', r), { y: (1 - c) * 40, op: c }); } });
