ALTER TABLE trips ADD COLUMN IF NOT EXISTS start_requested_at TIMESTAMPTZ;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS pickup_confirmed_at TIMESTAMPTZ;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS arrival_disputed_at TIMESTAMPTZ;
