import { useCallback, useEffect, useState } from 'react';
import * as adminApi from '../../api/admin.api';
import { Button, Card, EmptyState, Input, Skeleton, StatePill, toast } from '../../components/ui';
import type { SosAlert } from '../../types/admin.types';
import { getApiErrorMessage } from '../../utils/apiError';
import { formatDateTime } from '../../utils/format';

export function SosBoardPage() {
  const [rows, setRows] = useState<SosAlert[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [notes, setNotes] = useState<Record<string, string>>({});
  const load = useCallback(async () => { setError(null); try { setRows((await adminApi.listSos()).data); } catch (thrown) { setError(getApiErrorMessage(thrown, 'Could not load SOS alerts.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15_000); return () => window.clearInterval(timer); }, [load]);
  async function acknowledge(id: string) { setBusy(id); try { await adminApi.acknowledgeSos(id); toast.success('SOS acknowledged. Contact the rider now.'); await load(); } catch (thrown) { toast.error(getApiErrorMessage(thrown, 'Could not acknowledge SOS.')); } finally { setBusy(null); } }
  async function resolve(row: SosAlert, status: 'resolved' | 'false_alarm') { const note = notes[row.id]?.trim(); if (!note) { toast.error('Add a resolution note.'); return; } setBusy(row.id); try { await adminApi.resolveSos(row.id, note, status); toast.success(status === 'resolved' ? 'SOS resolved.' : 'SOS marked as false alarm.'); await load(); } catch (thrown) { toast.error(getApiErrorMessage(thrown, 'Could not resolve SOS.')); } finally { setBusy(null); } }
  return <main className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-2xl font-bold text-danger-600">SOS board</h1><p className="text-sm text-ink-500">Live safety queue · refreshes every 15 seconds · alerts never auto-dismiss.</p></div>{loading ? <div className="space-y-3"><Skeleton variant="card" /><Skeleton variant="card" /></div> : error && rows.length === 0 ? <EmptyState title="SOS board did not load" hint={error} action={{ label: 'Retry', onClick: load }} /> : rows.length === 0 ? <EmptyState title="No SOS alerts" hint="The safety queue is clear." /> : <div className="space-y-4">{rows.map((row) => <Card key={row.id} className={row.status === 'active' ? 'border-danger-600' : ''}><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{row.triggeredByName}</h2><StatePill state={row.status} /></div><a className="text-sm font-semibold text-cholo-700" href={`tel:${row.triggeredByPhone}`}>{row.triggeredByPhone}</a><p className="text-xs text-ink-500">{row.tripCode ?? 'Outside a trip'} · {formatDateTime(row.triggeredAt)}</p></div><a className="flex h-11 items-center rounded-xl border border-border px-4 font-semibold text-cholo-700" target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${row.lat}&mlon=${row.lng}#map=17/${row.lat}/${row.lng}`}>Open map</a></div>{row.status === 'active' && <Button className="mt-3" loading={busy === row.id} onClick={() => void acknowledge(row.id)}>Acknowledge</Button>}{['active', 'acknowledged'].includes(row.status) && <div className="mt-3 flex flex-wrap gap-2 border-t border-border pt-3"><Input containerClassName="min-w-64 flex-1" placeholder="Required resolution note" value={notes[row.id] ?? ''} onChange={(e) => setNotes((current) => ({ ...current, [row.id]: e.target.value }))} /><Button variant="secondary" loading={busy === row.id} onClick={() => void resolve(row, 'false_alarm')}>False alarm</Button><Button loading={busy === row.id} onClick={() => void resolve(row, 'resolved')}>Resolve</Button></div>}{row.resolutionNote && <p className="mt-3 text-sm text-ink-500">Resolution: {row.resolutionNote}</p>}</Card>)}</div>}</main>;
}
