import { useCallback, useEffect, useState } from 'react';
import * as adminApi from '../../api/admin.api';
import { Button, Card, EmptyState, Input, Skeleton, StatePill, toast } from '../../components/ui';
import type { TicketDetail, TicketStatus, TicketSummary } from '../../types/support.types';
import { getApiErrorMessage } from '../../utils/apiError';
import { formatDateTime } from '../../utils/format';
import { staggerStyle } from '../../utils/stagger';

export function SupportQueuePage() {
  const [rows, setRows] = useState<TicketSummary[]>([]); const [detail, setDetail] = useState<TicketDetail | null>(null); const [reply, setReply] = useState(''); const [internal, setInternal] = useState(false);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(null); try { setRows((await adminApi.listSupportTickets({ limit: 100 })).data); } catch (thrown) { setError(getApiErrorMessage(thrown, 'Could not load support queue.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function open(row: TicketSummary) { setBusy(true); try { setDetail(await adminApi.getSupportTicket(row.id)); } catch (thrown) { toast.error(getApiErrorMessage(thrown, 'Could not open ticket.')); } finally { setBusy(false); } }
  async function update(status: TicketStatus) { if (!detail) return; setBusy(true); try { await adminApi.updateSupportTicket(detail.id, { status, assignedToMe: true }); toast.success('Ticket updated.'); setDetail(await adminApi.getSupportTicket(detail.id)); await load(); } catch (thrown) { toast.error(getApiErrorMessage(thrown, 'Could not update ticket.')); } finally { setBusy(false); } }
  async function send() { if (!detail || !reply.trim()) return; setBusy(true); try { await adminApi.addSupportMessage(detail.id, reply.trim(), internal); toast.success(internal ? 'Internal note added.' : 'Reply sent.'); setReply(''); setDetail(await adminApi.getSupportTicket(detail.id)); } catch (thrown) { toast.error(getApiErrorMessage(thrown, 'Could not add message.')); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-6xl space-y-5"><div><h1 className="text-2xl font-bold">Support queue</h1><p className="text-sm text-ink-500">Prioritized customer cases, replies, and staff-only notes.</p></div>{loading ? <div className="space-y-3"><Skeleton variant="card" /><Skeleton variant="card" /></div> : error && rows.length === 0 ? <EmptyState title="Support queue did not load" hint={error} action={{ label: 'Retry', onClick: load }} /> : rows.length === 0 ? <EmptyState title="No support tickets" hint="The queue is clear." /> : <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><div className="space-y-2">{rows.map((row, index) => <Card key={row.id} variant="interactive" selected={detail?.id === row.id} onClick={() => void open(row)} className="animate-stagger-in" style={staggerStyle(index)}><div className="flex justify-between gap-2"><p className="font-semibold">{row.ticketNo}</p><StatePill state={row.status} /></div><p className="mt-1 text-sm">{row.subject}</p><p className="text-xs text-ink-500">{row.userName} · {row.priority} · {formatDateTime(row.createdAt)}</p></Card>)}</div><Card>{busy && !detail ? <Skeleton lines={5} /> : !detail ? <EmptyState title="Choose a ticket" hint="The full conversation will appear here." /> : <div className="space-y-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold">{detail.ticketNo} · {detail.subject}</h2><StatePill state={detail.status} /></div><p className="text-sm text-ink-500">{detail.userName} · {detail.userPhone} · {detail.tripCode ?? 'No trip linked'}</p></div><div className="max-h-96 space-y-2 overflow-auto rounded-xl bg-surface-alt p-3">{detail.messages.map((message) => <div key={message.id} className={`rounded-xl p-3 text-sm ${message.isInternalNote ? 'border border-marigold-500 bg-marigold-500/10' : 'bg-surface'}`}><p className="font-semibold">{message.senderName}{message.isInternalNote ? ' · Internal note' : ''}</p><p>{message.body}</p><p className="text-xs text-ink-500">{formatDateTime(message.sentAt)}</p></div>)}</div>{!['closed', 'resolved'].includes(detail.status) && <><Input label={internal ? 'Internal note' : 'Reply'} value={reply} onChange={(e) => setReply(e.target.value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={internal} onChange={(e) => setInternal(e.target.checked)} /> Staff-only internal note</label><div className="flex flex-wrap gap-2"><Button loading={busy} disabled={!reply.trim()} onClick={() => void send()}>Send</Button><Button variant="secondary" loading={busy} onClick={() => void update('waiting_user')}>Waiting for user</Button><Button variant="secondary" loading={busy} onClick={() => void update('resolved')}>Resolve</Button><Button variant="secondary" loading={busy} onClick={() => void update('closed')}>Close</Button></div></>}</div>}</Card></div>}</main>;
}
