export const CLIPS = [
  ['home-desk', 'home-desktop', ['load', 0.3], ['scene3', 0]],
  ['home-mob', 'home-mobile', ['scene1', -0.2], ['end', 0]],
  ['auth', 'auth', ['register', 0.4], ['otp', 9.5]],
  ['login', 'login', ['login', 0.3], ['end', 0]],
  ['p-where', 'ride-passenger', ['book-start', 0.6], ['stop-end', 3.4]],
  ['p-choose', 'ride-passenger', ['expand', -0.3], ['pay-end', 0.2]],
  ['p-extras', 'ride-passenger', ['promo-start', 0], ['women-end', 0.6]],
  ['p-match', 'ride-passenger', ['confirm-start', -0.6], ['enroute', 1.5]],
  ['d-match', 'ride-driver', ['confirm-start', -0.6], ['enroute', 1.5], 'ride-passenger'],
  ['p-enroute', 'ride-passenger', ['enroute', 0], ['near', 0.5]],
  ['p-pickup', 'ride-passenger', ['near', 0.2], ['in-progress', 1.5]],
  ['d-pickup', 'ride-driver', ['near', 0.2], ['in-progress', 1.5], 'ride-passenger'],
  ['p-share', 'ride-passenger', ['share-start', -0.3], ['share-end', 0.3]],
  ['f-share', 'ride-family', ['open', 1.2], ['end', 0]],
  ['p-sos', 'ride-passenger', ['sos-start', -0.2], ['sos-end', 0]],
  ['p-stop', 'ride-passenger', ['stop-ask', -0.3], ['complete', 2.5]],
  ['d-stop', 'ride-driver', ['stop-ask', -0.3], ['complete', 2.5], 'ride-passenger'],
  ['p-pay', 'ride-passenger', ['pay-due', 0.5], ['paid', 2.5]],
  ['p-receipt', 'ride-passenger', ['receipt', -0.2], ['rate-end', 1.6]],
  ['hub-trips', 'hub-trips', ['start', 0.2], ['end', 0]],
  ['hub-wallet', 'hub-wallet', ['start', 0.2], ['end', 0]],
  ['hub-promos', 'hub-promos', ['start', 0.2], ['end', 0]],
  ['hub-inbox', 'hub-inbox', ['start', 0.2], ['end', 0]],
  ['hub-places', 'hub-places', ['start', 0], ['end', 0]],
  ['hub-support', 'hub-support', ['start', 0], ['end', 0]],
  ['hub-receipt', 'hub-receipt', ['start', 0.2], ['end', 0]],
  ['hub-dark', 'hub-account', ['start', 3.2], ['bangla', 0]],
  ['hub-bn', 'hub-account', ['bangla', 2.2], ['end', 0]],
  ['d-apply', 'drv-apply', ['start', 0.2], ['submitted', 2.5]],
  ['d-docs', 'drv-docs', ['start', 0.2], ['end', 0]],
  ['d-vehicles', 'drv-vehicles', ['start', 0], ['end', 0]],
  ['d-online', 'ride-driver', ['online-start', 0], ['online-end', 0]],
  ['d-offer', 'ride-driver', ['offer', -0.2], ['accepted', 2.5]],
  ['d-start', 'ride-driver', ['slide:Slide to start trip', -1.2], ['started', 3]],
  ['d-earn', 'drv-earnings', ['start', 0.3], ['end', 0]],
  ['d-state', 'drv-statements', ['start', 0.3], ['end', 0]],
  ['d-withdraw', 'drv-withdraw', ['start', 0.3], ['end', 0]],
  ['a-dash', 'adm-dash', ['start', 0.3], ['end', 0]],
  ['a-analytics', 'adm-analytics', ['start', 0.3], ['end', 0]],
  ['a-comm', 'adm-commissions', ['start', 0.3], ['end', 0]],
  ['a-drivers', 'adm-drivers', ['start', 0.3], ['end', 0]],
  ['a-docs', 'adm-docs', ['start', 0.3], ['end', 0]],
  ['a-users', 'adm-users', ['start', 0.3], ['end', 0]],
  ['a-pricing', 'adm-pricing', ['start', 0.3], ['end', 0]],
  ['a-zones', 'adm-zones', ['dhaka', -0.5], ['end', 0]],
  ['a-surge', 'adm-surge', ['start', 0.3], ['end', 0]],
  ['a-promos', 'adm-promos', ['start', 0.3], ['end', 0]],
  ['a-payouts', 'adm-payouts', ['start', 0.3], ['end', 0]],
  ['a-sos', 'adm-sos', ['start', 0.3], ['end', 0]],
  ['a-disputes', 'adm-disputes', ['start', 0.3], ['end', 0]],
  ['a-reports', 'adm-reports', ['start', 0.3], ['end', 0]],
  ['a-support', 'adm-support', ['start', 0.3], ['end', 0]],
  ['a-audit', 'adm-audit', ['start', 0.3], ['end', 0]],
];
